### ISSUE TITLE
Error 500 tras regenerar link de inscripción

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#1008]
Tras regenerar el link de inscripción, las siguientes inscripciones producen un error 500, impidiendo que el estudiante se registre en el curso. 

@gastonprieto podrías aportar algún detalle más?

**Comment by julian-berbel** [comment]
Probé labo creando dos invitaciones mediante Invitation.import_form_json! y no obtuve ningún error, y classroom creando una invitación, dejando que expire, y creándola de nuevo y ambas veces la invitación pareció notificarse bien.
:thinking: no estoy seguro de que estará sucediendo...

**Comment by julian-berbel** [comment]
Sí tenemos un problema con que en algún momento, make_student_of! pasó a tomar una organizacion en vez de un slug, lo cual rompió la compatibilidad con las invitaciones las cuales funcionaban con un slug de organización/curso.

Esto no estaría relacionado a regeneración del link de inscripción, pero creo que de todos modos rompería todas las invitaciones, puede que se tratara de eso y que se estuviera regenerando un link fuera sólo coincidencia?

**Comment by flbulgarelli** [comment]
> Esto no estaría relacionado a regeneración del link de inscripción, pero creo que de todos modos rompería todas las invitaciones, puede que se tratara de eso y que se estuviera regenerando un link fuera sólo coincidencia?

Es un buen punto!

**Comment by gastonprieto** [comment]
Los casos que ví, me parece que eran problemas con gente, que ya estaba registrada en mumuki.io, por ejemplo con Facebook, pero después intentaba entrar a otra organización que tenía menos providers, ejemplo, solo aceptaba github, así que no sé si tiene que ver con la regeneración o no del link.

**Comment by flbulgarelli** [comment]
Fijate si podés reproducirlo haciendo que los links expiren y/o regenerando nuevos links. 

Si no lo podés reproducir, cerralo nomás.

**Comment by rodri042** [comment]
Sip, si entro a labo a una invitación que expiró tira 404 como corresponde.
Y si la regenero en classroom anda también

=> Cierro
