### ISSUE TITLE
Mejoras al kids layout

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-laboratory#1009]
Propuestas por @cucusita 

1. Que los tableros empiecen donde empieza el lienzo de blockly
2. Cambiar el color del enunciado para indicar si estás leyendo el enunciado, si estás leyendo la pista, si estás leyendo el error... etc
3. Que el breadcrumb tenga circulitos con el número de ejercicio (aplicaría a todos los layouts).

**Comment by aguspina** [comment]
4. Cuando te muestra el cartel de error, de alguna forma resaltar la existencia de la pista. Por ejemplo, titilando

**Comment by luchotc** [comment]
Necesitariamos ver, además, la disposición de todos los elementos dentro de la pantalla

![screenshot-2018-4-10 fundamentos practica primeros programas - mision imposible - mumuki](https://user-images.githubusercontent.com/11860076/38582535-6bf53d40-3ce6-11e8-9128-250b9f357001.png)

Qué les parece agregar un botón así para reiniciar contenido al toolbox, el cual obviamente pida confirmación

**Comment by luchotc** [comment]
Layout a implementar: 

![layout-kids-bottom](https://user-images.githubusercontent.com/11860076/38642646-07297bee-3db1-11e8-8312-2ca0e3ecebdb.png)

**Comment by luchotc** [comment]
@cucusita Thoughts?
Take into account that the navigation bars are supposed to be thinner.

**Comment by luchotc** [comment]
1. Estoy de acuerdo que estéticamente quedaría mejor, pero en tablet hay poca pantalla y está bueno aprovecharla al máximo. @fedescarpa?
2. Esto lo arrancó @fedescarpa con el de error, estaría bueno implementarlo para la pista también.
3. Opiniones de esto? @flbulgarelli 
4. En proceso por @fedescarpa 

El layout del último comentario ya quedaría implementado con lo del trashcan

**Comment by flbulgarelli** [comment]
> 3. Opiniones de esto? @flbulgarelli

Ok, puede andar! Pero tratemoslo por separado ya que afecta a toda la plataforma.

**Comment by luchotc** [comment]
Closing it because 3. was moved to another issue and the rest of the items were solved
