### ISSUE TITLE
The hint button is not very obvious in kids layout

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#1013]
The hint button should be more attention-getter, in order to quickly notice that the exercise comes with help. Perhaps it should have a different color, or it may blink from time to time.

**Comment by luchotc** [comment]
I agree. And the fact that the active button is darker than the other one is misleading.

**Comment by felipecalvo** [comment]
It blinks now, doesn't it?

**Comment by flbulgarelli** [comment]
You are right, fixed in #1320
