### ISSUE TITLE
Remove initial and final boards in success popup

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#1016]
It is cumbersome, requires extra space and does not add extra information

**Comment by luchotc** [comment]
@flbulgarelli If on error we are able to draw attention to the character to show the error and the expectations, maybe we can do the same on success and get rid of the pop-up altogether

**Comment by luchotc** [comment]
Decision:  Animate the character, highlight the speech bubble and show a success message. Wait a bit and then display the pop-up with just the corollary.
