### ISSUE TITLE
Add exercise number in progress bar

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-laboratory#1024]
This way it's more explicit which exercises the student has solved and to which exercise it's navigating to

**Comment by flbulgarelli** [comment]
![Screenshot from 2021-03-05 16-14-25](https://user-images.githubusercontent.com/677436/110162774-f1987400-7dcd-11eb-940c-f2c9dcdd8b8a.png)

This is something that can be completely achieved with organization's custom css and js, with no changes to the platform code. Closing.
