### ISSUE TITLE
Ejercicio funciona super raro

### ISSUE THREAD

**Issue by rgonzalezt** [mumuki/mumuki-laboratory#1043]
Ejercicio 14 "Más libros", lección 1, Objetos Tipado Estático.
https://sanluis.mumuki.io/exercises/3811-objetos-con-tipado-estatico-la-clase-el-objeto-y-el-mensaje-mas-libros
No pasa el test estando bien el ejercicio, tira error "419: unexpected token at '{"tag":"Send","conten'" 
Si le borras el método pasarMes() pasa el ejercicio en amarillo y te dice que falta ese método pero sólo ocurre si borras ese, sino tira el mismo error que antes.

**Comment by flbulgarelli** [comment]
@julian-berbel esto parece ser un bug de mulang o de la integración entre mulang y el runner de Java, ¿podrías mirarlo?

¿@rgonzalezt podrías mostrarnos el código con el que te sucedió eso?

**Comment by julian-berbel** [comment]
Por lo que veo, son tres bugs en uno:
1. Por un lado, mulang está fallando al parsear `this.horasParaIncunable = 20;`, lo cual es raro, porque no está fallando al parsear otros casos similares.
2. Por otro lado, no estamos contemplando el caso de que mulang finalize con una excepción al parsear el ast, lo cual causa el mensaje de error feo.
3. Por último, el expectations_hook falla de forma silenciosa, por lo que 1. ya venía fallando desde antes pero nunca nos enteramos, lo cual no está muy bueno.

Sobre el primero no hay mucho que decir, hay que implementar en el parseo de java lo que sea que esté causando el error.

Sobre el segundo, podemos hacer que el parseo devuelva nil cuando falla, de modo que continúe la ejecución con la solución normalizada.

Sobre el tercero, queda a decidir que hacer.
