### ISSUE TITLE
No funciona el mu-browser en la respuesta del html runner

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-laboratory#1045]
Hay que recargar la página para que se muestre, sino pasa lo siguiente

<img width="1440" alt="screen shot 2018-04-27 at 17 15 02" src="https://user-images.githubusercontent.com/4105740/39383142-8ae361e0-4a3e-11e8-8cf1-5986a018e582.png">

**Comment by flbulgarelli** [comment]
Was this fixes by #1059 @aguspina ?

**Comment by aguspina** [comment]
Yes
