### ISSUE TITLE
Los ejercicios con warnings no deberían lanzar pop up en kids

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-laboratory#1053]
Hoy en día cuando una solución da amarillo te lanza un popup (que no se puede cerrar) con el corolario para continuar al próximo ejercicio.

Si querés quedarte en el mismo ejercicio para solucionarlo no podés. Tenés que hacer 3 clicks:
*  En siguiente
*  Luego cerrar el contexto
*  Luego click en el ejercicio anterior

Es bastante molesto todo este proceso. Tal vez habría que repetir el comportamiento que tienen los ejercicios en rojo, explicando qué expectativas no se cumplieron dentro del box de enunciado.

@NadiaFinzi corregime si me faltó algo.

**Comment by flbulgarelli** [comment]
De acuerdo. Relacionado con https://github.com/mumuki/mumuki-laboratory/issues/1046

**Comment by NadiaFinzi** [comment]
Para ser más exactos, son 4 clicks, porque al volver al ejercicio anterior también hay que cerrar el contexto.

Y sí, creo que alguna explicación debería haber, aunque no sé si será tan claro o simple en todos los ejercicios.

**Comment by flbulgarelli** [comment]
Resuelto. Ya no se muestra un popup
