### ISSUE TITLE
Interpolations in default code should work with blocks 

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#1057]

**Comment by julian-berbel** [comment]
As for the laboratory side of things, there's no special behavior for interpolations in custom editor exercises so really it should work out of the box.

The thing is, the default content is mistakenly being sent twice on the exercise HTML, once interpolated and once not, and the uninterpolated content is being used in the gobstones runner causing interpolations to "not work".

This will require:
1. changing the Gobstones runner so it uses the interpolated default content
2. removing the uninterpolated content from the response here in labo to reduce traffic a bit
3. allowing interpolations input in bibliotheca
