### ISSUE TITLE
Cuando el status rendering verbosity es `verbose` el texto siempre dice unmeet expectations

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-laboratory#1058]
En este caso en el que se cumplieron TODAS, debería decir meet expectations

<img width="1094" alt="screen shot 2018-05-07 at 12 08 25" src="https://user-images.githubusercontent.com/4105740/39709121-656110e4-51ef-11e8-929c-fbfa532cc7b3.png">

**Comment by flbulgarelli** [comment]
El modo `verbose` está pensado para desarrollo. No vale la pena complejizar el código por eso.
