### ISSUE TITLE
Lots of JS errors in Web Console

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-laboratory#1060]
![errors](https://user-images.githubusercontent.com/11860076/39710160-627d13ac-51f2-11e8-8713-8b65fdaba96b.png)

Probably the because the muRender functions are called without asking if the components are actually present in the DOM

**Comment by rodri042** [comment]
Could you add more info about this? (when and where does it happen, how to reproduce it)

**Comment by flbulgarelli** [comment]
@luchotc?
