### ISSUE TITLE
Las expectativas no reconocen los procedimientos con "espacio"

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mumuki-laboratory#1078]
Estos ejercicios [4](https://bibliotheca.mumuki.io/#/guides/mumukiproject/mumuki-guia-gobstones-repeticion-simple-kids/exercises/4), [5](https://bibliotheca.mumuki.io/#/guides/mumukiproject/mumuki-guia-gobstones-repeticion-simple-kids/exercises/5) y [9](https://bibliotheca.mumuki.io/#/guides/mumukiproject/mumuki-guia-gobstones-repeticion-simple-kids/exercises/9), y algunos más que vendrán en la práctica de repetición simple, no reconocen en las expectativas a los procedimientos cuyos nombres contengan espacios. Ya se probó poner la expectativa con CamelCase, con el espacio correspondiente y con guión bajo, pero sigue tirando error.

@flbulgarelli

**Comment by flbulgarelli** [comment]
OK, ahí pude reproducir el problema. 

La cuestión es un poco más general (y preocupante, dado que afecta a gobstones textual también): sucede que cuando actualizamos la versión de Mulang, olvidamos migrar `gobstones-cli` para que la soporte (el único cambio que afecta a Gobstones es que `MuNull` se renombró a `None`).

**Comment by flbulgarelli** [comment]
Depends on https://github.com/gobstones/gobstones-cli/pull/5

**Comment by flbulgarelli** [comment]
@NadiaFinzi  para tener en cuenta: 

* en las expectativas, referenciá a los procedimientos en `CamelCaseMayuscula`, como venías haciendo. Por ejemplo, es `RecolectarPolen`
* Cuando hay parámetros, es como venías haciendo también: agregando un guión bajo. Por ejemplo `VolarAl_`
* Para chequear que usen `repeat`, la expectativa es `UsesRepeat` (y no `Uses:repeat`)

Seguí editando de esa forma; durante mañana el problema debería estar resuelto.

**Comment by flbulgarelli** [comment]
Resuelto en https://github.com/mumuki/mumuki-gobstones-runner/commit/79a8620e67f364d372fa5fe44602a17613edb320
