### ISSUE TITLE
Agregar botón para "desvestir" los tableros

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mumuki-laboratory#1086]
Habría que usar un asset por default que concuerde con las vestimentas, para identificar los casilleros "rotos"; junto con eso, agregar un botón para "desvestir" el tablero, pudiendo ver las bolitas y comparar entre el obtenido y el esperado. 

@flbulgarelli

**Comment by rodri042** [comment]
> Habría que usar un asset por default que concuerde con las vestimentas, para identificar los casilleros "rotos"

Esto en realidad se hace desde la vestimenta... como el orden de las reglas importa, se puede agregar una al final que agarre todo (red: "*", green: "*", black: "*", blue: "*") con la imagen deseada para celda "rota".

**Comment by flbulgarelli** [comment]
> Esto en realidad se hace desde la vestimenta... como el orden de las reglas importa, se puede agregar una al final que agarre todo red: "*", green: "*", black: "*", blue: "*" con la imagen deseada para celda "rota".

Sí, sí, Eso es cierto. En realidad la parte importante  del issue a nivel desarrollo es la segunda: el botón de desvestir.
