### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by carla464** [mumuki/mumuki-laboratory#1099]
Hola, no puedo ingresar al sistema. Intento iniciar sesion y me sale error 500.

**Comment by flbulgarelli** [comment]
¡Hola! ¿Podrias darnos más detalles por favor?

**Comment by carla464** [comment]
He intentado muchas veces iniciar sesion para empezar con la leccion 1 de
programadores 3.0 pero me sale error 500. No se que hacer.

**Comment by flbulgarelli** [comment]
Ok, comunicate por favor con soporte@mumuki.org
