### ISSUE TITLE
Finalizada una guía, si se vuelve a hacer un ejercicio correctamente, no se puede salir del cuadro de festejo

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mumuki-laboratory#1105]
Terminé todos los ejercicios de una guía, y volví a resolver uno. Al terminar (correctamente) salta el cuadro de festejo, pero no tiene botón para continuar porque no existen más ejercicios ni guías subsiguientes. 

![image](https://user-images.githubusercontent.com/7552150/42532149-5b9f6c6e-845c-11e8-9e5c-0321c080f75c.png)

@flbulgarelli

**Comment by Gustrucco** [comment]
Añado algo a este issue. Lo mismo sucede al realizar el último ejercicio de un capítulo de primaria. No da la opción de continuar con el siguiente.

**Comment by julian-berbel** [comment]
> o preferirían agregar un botón para los casos en los que no se tiene un siguiente ejercicio?

Recién me dijo @flbulgarelli  que por el momento preferiría esto (y teniendo en cuenta que sólo debería aparecer en modals, en una guía de adultos no debería aparecer)

**Comment by flbulgarelli** [comment]
PD: ¿hay algún screenshot?
