### ISSUE TITLE
Limit submissions size in exam exercise

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-laboratory#1108]
@flbulgarelli We should be able to limit the number of submissions submitted in exam's exercise. We could use the submissions_count in the assignment field.

@fedescarpa this should be done in bibliotheca too.

**Comment by luchotc** [comment]
@aguspina Should we implement this? The threshold is defined globally for that exam or should it be customizable for each exercise in the exam?

**Comment by flbulgarelli** [comment]
I'd not define this in bibliotheca, but when creating the exam from classroom. That way, each teacher could define different attempts count for the same exam.

**Comment by flbulgarelli** [comment]
> @aguspina Should we implement this? The threshold is defined globally for that exam or should it be customizable for each exercise in the exam?

To keep things simple, I'd define the threshould for the whole guide when enabling it as an exam.

**Comment by Gustrucco** [comment]
We should be able to configure:
* maximum number submissions for code exercises and for choice's exercises separately.
* a counter in the student's view of the exercise, so he or she could see how many attempts has made.
