### ISSUE TITLE
'I need help' dropdown shows no options for organizations with no forum nor issue reporting

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mumuki-laboratory#1113]
![image](https://user-images.githubusercontent.com/11720274/43007365-7e2289ec-8c0e-11e8-93d5-75a0b0a1325a.png)

We could either not show the dropdown when there are no options (don't really like this one) or have issue reporting be available if enabled or if there's no forum.

**Comment by flbulgarelli** [comment]
I agree this is an issue. 

However, I prefer that if there are no help options active, than no dropdown is rendered. 

Also, as a side questions: is still the community option available? Forum should no remove it, but be a complement

**Comment by luchotc** [comment]
Yes, the community option is still available.
I'm on it!

**Comment by flbulgarelli** [comment]
Great!
