### ISSUE TITLE
no me deja iniciar sesion

### ISSUE THREAD

**Issue by gbernardini** [mumuki/mumuki-laboratory#1121]
Me da un error 500

failure?message=server_error&strategy=auth0:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by flbulgarelli** [comment]
Buenas!

Te sigue sucediendo?

**Comment by gbernardini** [comment]
Sigue sin dejarme hacer login con usuario y contraseña. Ya cambie la contraseña y tengo registrado el mail pero no me funcionó. Me dejó hacer login con Google.

**Comment by flbulgarelli** [comment]
¿Probaste con otro navegador? ¿Y en incógnito?

**Comment by gbernardini** [comment]
Si, probé en modo incógnito de chrome y con safari y se repite el error

**Comment by flbulgarelli** [comment]
¡Hola! El problema debería estar resuelto en mumuki.io
