### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by mari967** [mumuki/mumuki-laboratory#1128]
Cuando trato de ver el ejercicio 4 (dominio) de la lección 9 de programación lógica, me aparece ese error en la página.
Solo ocurre con este ejercicio.

**Comment by julian-berbel** [comment]
No lo estoy pudiendo reproducir. :thinking:  Te pido un poco más de información:

Te sigue pasando o fué sólo una vez?
Que navegador usaste?
Entraste desde la interfaz o seguiste algún link en particular?

**Comment by flbulgarelli** [comment]
Ya lo reprodujimos. Estamos trabajando en eso.

**Comment by flbulgarelli** [comment]
Listo. Probá ahora.

**Comment by flbulgarelli** [comment]
El motivo es que el campo `submission_status` de `Assignment` era nullable (por un error https://github.com/mumuki/mumuki-laboratory/blob/2217da49267ee5fdea68c27e1b9eda0bb65730df/lib/mumuki/laboratory/status.rb#L19). A partir de la versión `5.6.0` esto ya no es así, y fue necesario migrar los datos.
