### ISSUE TITLE
Me tira error y puse las funciones correctamente

### ISSUE THREAD

**Issue by neverkas** [mumuki/mumuki-laboratory#1142]
Hay algo mal? Tampoco me corrigió...
function anterior(n){
return n-1;
}
function triple(n){
return n*3;
}
function anteriorDelTriple(n){
return anterior(triple(n));
 }

**Comment by flbulgarelli** [comment]
¡Hola! ¿Qué error produjo? 

Si te estás refiriendo al ejercicio https://mumuki.io/exercises/2759-programacion-imperativa-funciones-y-tipos-de-datos-funciones-uso, esa solución está funcionado.
