### ISSUE TITLE
Login is not working on embedded mode

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#1149]
The culprit is here: https://github.com/mumuki/mumuki-laboratory/blob/aaa5fb5410bfcad190b3a22a01eea2fd9d3e04f3/app/controllers/exercises_controller.rb#L13

This action should be performed on every route, or at least in the login route

**Comment by rodri042** [comment]
I tested locally and it worked: https://youtu.be/DZL8nF5vuus <--- am I doing something wrong?

Login with providers such as Google or Facebook doesn't work since they forbid iframes.

**Comment by fedescarpa** [comment]
Closing
