### ISSUE TITLE
No aparecen las flechas para bajar el texto de la consigna

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mumuki-laboratory#1164]
@fedescarpa 

No están las flechas para subir o bajar el texto que no entra completo en el globo de la consigna/ayuda.

![image](https://user-images.githubusercontent.com/7552150/44172128-a228b600-a0b2-11e8-80d8-f6a6fb2889c4.png)

**Comment by fedescarpa** [comment]
@flbulgarelli creo que rodri había arreglado eso hace un mes, podés confirmarme eso... https://www.youtube.com/watch?v=LDaxn0Xji4U

**Comment by flbulgarelli** [comment]
> @flbulgarelli creo que rodri había arreglado eso hace un mes, podés confirmarme eso... https://www.youtube.com/watch?v=LDaxn0Xji4U

Sí, pero luego se modificó ese comportamiento porque el scrolling era molesto e impredecible. Entonces no sé como quedó realmente.

**Comment by flbulgarelli** [comment]
Alternativamente, cuando supera el tamaño de la burbuja y no hay un párrafo que corte al texto, podríamos utilizar elipsis (...), además de mostrar la flecha, para reforzar la idea de que el texto continúa.
