### ISSUE TITLE
Bad submission results

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mumuki-laboratory#1180]
On submission, the results displayed are the assignment status *previous* to the current submission.

**Comment by flbulgarelli** [comment]
Is this happening on master or on latest version?

**Comment by flbulgarelli** [comment]
If it is happening on master only, this is with no doubts related to https://github.com/mumuki/mumuki-laboratory/pull/1175

**Comment by julian-berbel** [comment]
it's happening on master so yeah, that's likely the case

**Comment by flbulgarelli** [comment]
Also, added tests for `try_submit_solution!` in 9e7ebfb4ab3a84b67371a639a2783c005f81d4d7, which was the culprit here.
