### ISSUE TITLE
Al entrar al issue de http parte 2 (discusion 937, 936 y 937) el servidor responde con un 500.

### ISSUE THREAD

**Issue by argdaniellarrea** [mumuki/mumuki-laboratory#1191]
Se reproduce en una consulta abierta  (a la fecha del 15/09/2018), las tres consultas son de HTML el ejercicio http-parte-2.

**Comment by julian-berbel** [comment]
Hola Daniel!

Este error ya se solucionó, pero todavía no se deployó la solución. Lo estaremos haciendo en estos días.

Gracias!
