### ISSUE TITLE
Se queda recargando la página con error 500

### ISSUE THREAD

**Issue by rgonzalezt** [mumuki/mumuki-laboratory#1193]
Cuando querés entrar a un ejercicio de un exámen da error 500 y la pantalla se queda "titilando".
Este es el error que dice:

Uncaught Error: rails-ujs has already been loaded!
    at Object.t.start (application-fee16bf106caa345e9b080041ec02641c9c947854a2d8cbb010c8f8cafb14762.js:11)
    at application-fee16bf106caa345e9b080041ec02641c9c947854a2d8cbb010c8f8cafb14762.js:11
    at application-fee16bf106caa345e9b080041ec02641c9c947854a2d8cbb010c8f8cafb14762.js:11
    at application-fee16bf106caa345e9b080041ec02641c9c947854a2d8cbb010c8f8cafb14762.js:11
    at application-fee16bf106caa345e9b080041ec02641c9c947854a2d8cbb010c8f8cafb14762.js:11

**Comment by julian-berbel** [comment]
I need some more context :thinking: exams seem to be working fine in development :thinking:

**Comment by julian-berbel** [comment]
not sure why the rails-ujs thing was happening but it seems to be ok. The 500 error was fixed in #1199 too, so I'm closing this.
