### ISSUE TITLE
Gobstones bloques no soporta el error expect_endless_while: true

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mumuki-laboratory#1207]
Ante un ejercicio que tendría que romper por timeout, si bien rompe correctamente, dice que no se puede ejecutar la solución. Dejo la imagen donde se ve el resultado.

![image](https://user-images.githubusercontent.com/7552150/45907501-7cd44980-bdce-11e8-8b4a-ada8fa2127c2.png)

@julian-berbel

**Comment by NadiaFinzi** [comment]
Estos dos ejercicios deberían romper por timeout, pero dar verde porque es el error esperado. Sin embargo, están tirando que la solución no se puede ejecutar (tal como se ve en la imagen del comentario anterior. Dejo los links de biblio y labo de cada uno:

Ejercicio 1: [biblio](https://bibliotheca.mumuki.io/#/guides/mumukiproject/mumuki-guia-gobstones-repeticion-condicional-ii-kids/exercises/1), [labo](https://mumuki.io/primaria/exercises/5580-repeticion-condicional-practica-maria-la-paz-un-paso-pa-atras).

Ejercicio 2: [biblio](https://bibliotheca.mumuki.io/#/guides/mumukiproject/mumuki-guia-gobstones-repeticion-condicional-ii-kids/exercises/2), [labo](https://mumuki.io/primaria/exercises/5589-repeticion-condicional-practica-al-infinito).

**Comment by rodri042** [comment]
@NadiaFinzi esto se arregló en https://github.com/mumuki/mumuki-gobstones-runner/pull/125 pero parece que todavía no fue subido a producción

**Comment by flbulgarelli** [comment]
Hola! el problema @rodri042 es que ya está desplegado y sigue pasando :/

**Comment by flbulgarelli** [comment]
Otro problema más raro aún es que en https://mumuki.io/primaria/exercises/5589-repeticion-condicional-practica-al-infinito, si se envíe el código tal cual está, da verde (pero debería fallar, porque falta un bloque)

**Comment by rodri042** [comment]
Creo que el problema es que el YAML está mal formateado:

```
check_head_position: false
examples:
 - initial_board: |
     GBB/1.0
     size 2 2
     cell 0 1 Negro 4 Rojo 4 
     cell 1 1 Azul 6 Rojo 4 
     cell 0 0 Negro 4 Rojo 4 
     cell 1 0 Negro 4 Rojo 4 
     head 1 1
   expect_endless_while: true
```

`expect_endless_while` debería ir al principio sin ningún espacio antes

**Comment by flbulgarelli** [comment]
Comprobado, es lo que dice Rodri. Corrigiendo el test anduvo bien. 

El problema ahora es que la UI se cuelga unos segundos antes de dar verde.
