### ISSUE TITLE
Se está rompiendo el toolbox de primaria

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mumuki-laboratory#1210]
Encontramos ejercicios en los que el toolbox se veía distinto a como se había definido. Revisando guías viejas que andaban bien, vimos que pasaba lo mismo. En ciertos ejercicios no se está respetando el xml definido. 

Así se ve el toolbox de una guía:
![image](https://user-images.githubusercontent.com/7552150/45980742-37f81f00-c029-11e8-99fb-a94485a271e4.png)

Y así está definido el toolbox:
![image](https://user-images.githubusercontent.com/7552150/45980839-75f54300-c029-11e8-94e2-4b558d87d9c6.png)

Es fundamental que se arregle cuanto antes porque las actuales categorías confunden mucho y tienen bloques que no deberían poder usar. 

@flbulgarelli @fedescarpa

**Comment by NadiaFinzi** [comment]
Encontré estos cambios hechos en blocly, pero los apliqué a una guía de prueba y no se modificó nada.

Cambié `<category name="Procedimientos primitivos">` por `<category name="Procedimientos primitivos" gbs_custom="PRIMITIVE_PROCEDURES">`. Lo mismo hice con las funciones primitivas. 

![image](https://user-images.githubusercontent.com/7552150/45981250-bdc89a00-c02a-11e8-95cd-e88ec05d2ff1.png)

**Comment by flbulgarelli** [comment]
@rodri042 alguna idea de qué puede estar pasando?

**Comment by rodri042** [comment]
Eso fue para soportar otros nombres para la categoría procedimientos primitivos en Gobstones Web, pero **debería** ser retrocompatible. Seguro lo que pasó fue que rompí alguna otra cosa, no parece estar dándole bola al toolbox default.

Ahora lo reviso. Mientras tanto (si ahora mismo está roto) para mí habría que fijar la versión que está en el gemspec

**Comment by NadiaFinzi** [comment]
Me dí cuenta que el toolbox se rompe justamente cuando hay procedimientos primitivos. Dejo el [video](https://youtu.be/rOYPztwthi8) demostrándolo. Imagino que con las funciones primitivas debe pasar lo mismo. 

En este otro [video](https://youtu.be/wtgl11qMmwg) se ve que el toolbox llega a cargarse más largo, y automáticamente se acorta pisándose por el toolbox incorrecto.

**Comment by rodri042** [comment]
Arreglado en https://github.com/mumuki/mumuki-gobstones-runner/pull/124.

Dejé fija la versión del minor por las dudas. El breaking change que se me pasó es que para que el toolbox conserve los cambios tiene que setearlo en la config del toolbox como `defaultToolbox` en vez de llamar manualmente a `setDefaultToolbox` como venía haciendo el runner.
