### ISSUE TITLE
When exam is close to expire, it should be refreshed more frequently

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#1251]

**Comment by luchotc** [comment]
@flbulgarelli What's the goal of this one?

**Comment by flbulgarelli** [comment]
Currently, the timer is refreshed once per minute. However, when less than a minute is left, it should be refreshed once per second

**Comment by luchotc** [comment]
Currently it is refreshed once per second: https://github.com/mumuki/mumuki-laboratory/blob/master/app/assets/javascripts/mumuki_laboratory/application/timer.js#L9. 
Or are you referring to something else?

**Comment by flbulgarelli** [comment]
In that case, this issue may be old. Could we test it is working properly?

**Comment by luchotc** [comment]
It is. Actually, just a week ago we've added a page reload to "kick" the student from the exam when the time expires. cc @Gustrucco 
I'm closing this one then :smile:
