### ISSUE TITLE
¿Entregar OpenBadges al completar una lección o capítulo?

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-laboratory#1261]
Más info en https://openbadges.org/get-started/issuing-badges/

**Comment by flbulgarelli** [comment]
@felipecalvo @luchotc I think we should close this one since all the gamification feature implemented during 2020 replace this concept.

**Comment by felipecalvo** [comment]
Sure, medals kinda replace this. We could add some more, by the way.

Something else we planned - but didn't get around to implement - was adding badges or site-related (but not content-related) medals, such as posting # times in the forum, completing # exercises, getting to level #, etc.
