### ISSUE TITLE
Profile menu is difficult to read

### ISSUE THREAD

**Issue by JessSaavedra** [mumuki/mumuki-laboratory#1262]
In wide screens, profile menu opens on the right when there is no much free space, forcing the user to scroll to see the whole menu.

![profilemumuki](https://cloud.githubusercontent.com/assets/7197057/25690536/99d0acd0-3068-11e7-8e5e-57e3fb69b370.png)

**Comment by rodri042** [comment]
I can't reproduce this issue. @JessSaavedra can you confirm if this is still happening?

**Comment by flbulgarelli** [comment]
@felipecalvo I think you have already fixed this issue by changing the opening direction of the menu, haven't you?

**Comment by felipecalvo** [comment]
I don't think I changed anything, yet at the same time I've never seen it occur, so... closing?
