### ISSUE TITLE
Posibilidad de modificar la foto de perfil

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-laboratory#1263]
Dado que los login sociales son muy poco usados en organizaciones privadas, las fotos de perfil son prácticamente inexistentes. Sería bueno poder cambiarla.

**Comment by rodri042** [comment]
@flbulgarelli dónde deberíamos guardar las fotos subidas? tenemos algún servicio de storage para eso?

**Comment by flbulgarelli** [comment]
No, pero deberíamos utilizar la interfaz genérica de `ActiveStorage`, que hace que puedas guardarlas en disco en un  servicio S3-compatible de forma transparante.

**Comment by flbulgarelli** [comment]
Eso va a implicar actualizar labo (y domain y biblio) a al menos a rails 5.2 (estamos en 5.1)

**Comment by flbulgarelli** [comment]
@felipecalvo @luchotc I think we should close this issue since we moved to avatars as profile image customization.
