### ISSUE TITLE
Don't allow file names with / in multi-file tabs

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#1270]
Using slashes in file names is not supported by mumukit.

**Comment by rodri042** [comment]
We should use this sanitization: https://github.com/mumuki/mumukit/commit/c8a56610e98f5b77bc7360d8b2ac6671990f5c0b#diff-827fb7048d358a0c69f41a0840c6e9c4R3

**Comment by flbulgarelli** [comment]
Great! Perhaps we could check this too: https://github.com/madrobby/zaru
