### ISSUE TITLE
Solution box shows another exercise's code after refreshing

### ISSUE THREAD

**Issue by felipecalvo** [mumuki/mumuki-laboratory#1271]
I _think_ these are the steps to reproduce the bug:

- Send a solution in exercise A.
- Open exercise B, then refresh.
- Now solution sent in exercise A will appear.

Solution in exercise A
![image](https://user-images.githubusercontent.com/11304439/51405481-305b0980-1b35-11e9-8282-67edf9f43f79.png)

Open exercise B
![image](https://user-images.githubusercontent.com/11304439/51405517-45d03380-1b35-11e9-81dd-348b775e24cd.png)

After refreshing, solution A appears
![image](https://user-images.githubusercontent.com/11304439/51405690-c7c05c80-1b35-11e9-804d-b8f3472ed674.png)

Sometimes it might be the other way around; solution sent in exercise B might appear in A. Not quite sure how or why.

**Comment by rodri042** [comment]
I couldn't reproduce that behavior.

It seems strange since that value comes from the assignment's solution ([here](https://github.com/mumuki/mumuki-domain/blob/master/app/models/assignment.rb#L177)).

@felipecalvo can you try to break it again, maybe recording a video to see what's going on with more detail?

**Comment by felipecalvo** [comment]
https://youtu.be/iH6l6gHjS-4

I refreshed on many other exercises after the video and the `trasladar` solution appeared on all of them as well.

**Comment by felipecalvo** [comment]
Ok, I think I know why no one has noticed this bug before: I'm using Firefox. Can't reproduce it in Chrome.

:fox_face:

**Comment by flbulgarelli** [comment]
Pasos con los que logré reproducirlo (en Firefox): 

1. Entro a un ejercicio despues de darle click a "Continuar" en el anterior.
2. El ejercicio arranca con un editor vacío (OK)
3. Recargo la página, sigue estando bien
4. Edito el ejercicio en la biblioteca
5. Recargo con F5: se reproduce el bug al cargarse el contenido de un ejercicio previo. 

A partir de este putno, si se recarga la pantalla con F5 el bug persiste, pero si se recarga con CTRL + SHIFT + R o similar, o si se vuelve al ejercicio anterior y luego se presiona el botón siguiente, el problema se resuelve. 

Si se borra la caché de Submissions en JS no hay cambios. 

Este comportamiento hace aun más pensar en un problema de turbolinks específico de Firefox

**Comment by felipecalvo** [comment]
I couldn't reproduce it this time, neither with my instructions nor yours. I'm not sure what I'm supposed to do on step 4 though.

In any case, this might be a Firefox bug related to forms instead. Makes sense or we would have seen it in other browsers before.

See this issue: https://github.com/turbolinks/turbolinks/issues/536. They've gone as far as creating a page to test this behaviour and it correlates to what we've been seeing in our editor: https://horse-eastern-coral.glitch.me/

They opened a bug report here last year https://bugzilla.mozilla.org/show_bug.cgi?id=1630942 but there's been no progress... though at least its existence was acknowledged a month ago.

I don't think there's much we can do. My first thought was adding some random element to each form so the browser understands they're different - but then I remembered the form id is already random! Maybe adding some other random element to the textarea itself?

**Comment by felipecalvo** [comment]
Nevermind, I immediately managed to reproduce as the original post said by sending both submissions. I might try this random thing I mentioned

**Comment by felipecalvo** [comment]
Alright, randomizing more IDs didn't work, but this :arrow_up: might do it. Please check it out.
