### ISSUE TITLE
Console tab should appear selected by default when 'Show extra code' is on

### ISSUE THREAD

**Issue by felipecalvo** [mumuki/mumuki-laboratory#1275]
This is something that started happening recently. I'm only seeing it on exercises which have both Console and Library tabs.

Open up an exercise you haven't opened in a while and no tab will be selected by default, even though the console is seen

![image](https://user-images.githubusercontent.com/11304439/51689643-d5626000-1fd5-11e9-9c84-fce850a9fd44.png)

When Console is clicked, then it'll be highlighted and it stays like that

![image](https://user-images.githubusercontent.com/11304439/51689706-f6c34c00-1fd5-11e9-817d-f2ab7772fcc2.png)

Here are a couple exercises on which I'm seeing this
https://mumuki.io/staging/exercises/4293-programacion-con-objetos-clases-e-instancias-al-menos-tenemos-salud
https://mumuki.io/staging/exercises/2741-programacion-imperativa-listas-sumatorias-primera-parte

**Comment by rodri042** [comment]
It's works well in my development environment, and the staging link gives me a 403 error. @flbulgarelli can you give me permissions?

**Comment by flbulgarelli** [comment]
Done @rodri042
