### ISSUE TITLE
Traducción faltante cuando aborta un query

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mumuki-laboratory#1317]
translation missing: es.submission.try_again

Probado en https://mumuki.io/central/exercises/1916-programacion-funcional-recursividad-introduccion

**Comment by felipecalvo** [comment]
The translation does exist [here](https://github.com/mumuki/mumuki-domain/blob/4e52b4f5a6f58a604751647378b3440041161039/lib/mumuki/domain/locales/submission.es.yml#L3); it's not working on any language

![image](https://user-images.githubusercontent.com/11304439/57257222-2b13c300-702f-11e9-9ca2-f40e53b343cd.png)

![image](https://user-images.githubusercontent.com/11304439/57257175-12a3a880-702f-11e9-965f-c84adf054ecd.png)

**Comment by flbulgarelli** [comment]
That means that the issue here is that those translations are not being loaded at all. It may be a bug in laboratory imports.

**Comment by felipecalvo** [comment]
I made it work after changing and trying quite a lot of stuff so I'll try to break down what is needed and what isn't before committing anything.

![image](https://user-images.githubusercontent.com/11304439/57404169-b7e68a00-71b1-11e9-9226-1f0c6dcdc237.png)
