### ISSUE TITLE
Messages should be organic as well

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-laboratory#1318]
In the user profile, the messages aren't organic like discussions. 
In this case it's even worse, because all the messages links are formed with the current organization. 
So if received a message in an exercise of organization_1 and another in an exercise of organization_2 and these exercises aren't shared between organizations, both links will be formed with the current organization, so one of them will lead to a 404 error.

**Comment by luchotc** [comment]
This issue will be solved automatically when the assignments are related directly to one organization

**Comment by flbulgarelli** [comment]
@luchotc is this related to the new notification's model introduced by @faloi as part of #1541 ?

**Comment by flbulgarelli** [comment]
Closed by https://github.com/mumuki/mumuki-laboratory/pull/1581
