### ISSUE TITLE
Adding a 401 animation?

### ISSUE THREAD

**Issue by felipecalvo** [mumuki/mumuki-laboratory#1329]
I'm not sure how to trigger a 401 error so I just pasted its code in the 404 method and this is what I got:

![image](https://user-images.githubusercontent.com/11304439/58105130-603a1c80-7bbc-11e9-81d7-b1020b8098e2.png)

(no surprise since we're [trying to load](https://github.com/mumuki/mumuki-laboratory/blob/master/app/views/errors/unauthorized.html.erb#L3) an image that doesn't exist)

However, is this something that could happen in practice? Are we actively returning 401 error codes or are we just using 403? Should we add animations for this code error?

**Comment by flbulgarelli** [comment]
I am not sure if we are actually throwing that status. If that is the case, I vote for adding a new image. 

But in any case, we could use the same images that for 403 animation

**Comment by luchotc** [comment]
Actually, we are using it now, so nice one @felipecalvo :smile: 
Fixed by https://github.com/mumuki/mumuki-laboratory/commit/ba050ee2bd497acf7927928a42dd0110937856bf
