### ISSUE TITLE
Reiniciar no funciona

### ISSUE THREAD

**Issue by camils1** [mumuki/mumuki-laboratory#1347]
Un amigo avanzo mas que yo con mi usuario y necesito reiniciar las lecciones. El boton de reiniciar me tirar un error 500

**Comment by flbulgarelli** [comment]
Hola! Te está pasando en todos los ejercicios o con alguno en particular?

**Comment by camils1** [comment]
Hola! Con todos los ejercicios. Estoy usando el boton de reiniciar las lecciones y no me funciona. Graciass

Camila Barletta
+5491169709767

**Comment by luchotc** [comment]
Hola! Muchísimas gracias por reportar el error!
El mismo ya se encuentra solucionado.

Saludos :smile:
