### ISSUE TITLE
Falla la regla de asistencia de "Alguna de las expectativas falla"

### ISSUE THREAD

**Issue by Gustrucco** [mumuki/mumuki-laboratory#1359]
https://github.com/MumukiProject/mumuki-guia-python-variables-y-procedimientos/commit/3c4a02bed3eb9ae606f0e65dd2bb39d9f5be0861?diff=split

**Comment by flbulgarelli** [comment]
Apparently this rule works properly.

This is not displaying the message in your example because your assignment has not passed with warnings, but failed instead, and this rule only works with that kind of assignments
