### ISSUE TITLE
Reify progress

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-laboratory#1363]
Currently, we can only know the status of an exercise, and through some calculations, know if a guide was completed.
We should reify the concept of progress and have it denormalized for every content that a student can complete (book, chapter, lesson). Take into account that the assignment won't be shared anymore between organizations, so we can't just link the progress to a book, for example. It should link the student, the book and the organization in which that progress was made.

**Comment by julian-berbel** [comment]
I'll leave here what we talked about today:
![image](https://user-images.githubusercontent.com/11720274/67987636-afc15180-fc0c-11e9-9c4e-d929e2033ace.png)
