### ISSUE TITLE
Clase 4 - Incorporando Bootstrap -> Error 500

### ISSUE THREAD

**Issue by ariel-gallardo** [mumuki/mumuki-laboratory#1369]
https://mumuki.io/blend.digitalhouse/exercises/5253-html-css-clase-4-expertise-y-bootstrap-incorporando-bootstrap
![Captura de pantalla_2019-10-25_15-11-18](https://user-images.githubusercontent.com/38444032/67594041-dd545980-f739-11e9-8811-936d5e0d9311.png)

**Comment by luchotc** [comment]
Hola, muchas gracias por el reporte!
Lo estamos analizando

**Comment by luchotc** [comment]
Ya está solucionado. Gracias por el reporte nuevamente.

Saludos!
