### ISSUE TITLE
Não consigo acessar a página do desafio do Santander Coders

### ISSUE THREAD

**Issue by tpossatt** [mumuki/mumuki-laboratory#1371]
Me enviaram o link por e-mail do site que estaria hospedados os desafios do programa, quando entrei aparecia o erro 404.

**Comment by flbulgarelli** [comment]
Hi! This repository contains the source code of the Mumuki Plataform. It is aimed to track changes, suggestions and bug reports. It assists the development process.

Please do not submit issues related to access to the mumuki.io service or any other Mumuki Plataform deployment.

Please contact the institution that invited you to the course you are trying to enroll.

Thanks!
