### ISSUE TITLE
Não consigo acessar o teste

### ISSUE THREAD

**Issue by brunnogpcosta** [mumuki/mumuki-laboratory#1372]
https://mumuki.io/br.digitalhouse.neon.santander/exams/7738b48017224826

Acesso com meu email, o que tenho usado para fazer o curso online. Creio não estar funcionando por eu ter recebido antes de terminar a etapa online.

Podem me ajudar?

**Comment by flbulgarelli** [comment]
Hi! This repository contains the source code of the Mumuki Plataform. It is aimed to track changes, suggestions and bug reports. It assists the development process.

Please do not submit issues related to access to the mumuki.io service or any other Mumuki Plataform deployment.

Please contact the institution that invited you to the course you are trying to enroll.

Thanks!
