### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by alfredo-vazquez-25** [mumuki/mumuki-laboratory#1390]
Buen día, me comunico porque quiero entrar a la plataforma mendoza educa y no me permite entrar.

![imagen](https://user-images.githubusercontent.com/54646061/78452862-5c907680-7664-11ea-92e1-b813bbda7ec9.png)

**Comment by flbulgarelli** [comment]
Hola Alfredo!

Estamos investigando

**Comment by flbulgarelli** [comment]
Hola Alfredo! 

No hay contenidos en esta plataforma para que puedas ver por el momento. 

Saludos!

**Comment by alfredo-vazquez-25** [comment]
Hola Franco!
Ok. gracias.
Saludos
