### ISSUE TITLE
El editor de multiple files no está mostrando bien las opciones de edición de código.

### ISSUE THREAD

**Issue by rgonzalezt** [mumuki/mumuki-laboratory#1415]
En los editores de ejercicios, se muestran tres opciones en la esquina superior derecha:

![image](https://user-images.githubusercontent.com/11671943/84304577-186f9580-ab2f-11ea-965d-49526677261f.png)

Sin embargo, estas opciones no se visualizan correctamente en los editores de ejercicios del estilo `multiple files`:

- La opción `pantalla completa` ![image](https://user-images.githubusercontent.com/11671943/84305173-f9253800-ab2f-11ea-8aff-e7ef39d3dc84.png) no deja crear nuevas páginas ya que tapa el **+**.
- No aparece la opción de `formatear código` ![image](https://user-images.githubusercontent.com/11671943/84305089-d430c500-ab2f-11ea-838b-825b1fb2eeae.png).

Así se ve:

![image](https://user-images.githubusercontent.com/11671943/84304661-363cfa80-ab2f-11ea-923c-2248a06dd60d.png)

**Comment by flbulgarelli** [comment]
> Sin embargo, estas opciones no se visualizan correctamente en los editores de ejercicios del estilo `multiple files`:
> 
> * La opción `pantalla completa` ![image](https://user-images.githubusercontent.com/11671943/84305173-f9253800-ab2f-11ea-8aff-e7ef39d3dc84.png) no deja crear nuevas páginas ya que tapa el **+**.

Esto es un bug importante y un poco tonto :cry: , porque se consideró y se probó pero en algún punto se nos pasó. Ya mandé un PR para resolverlo, ¡gracias por avisar @rgonzalez! 


> * No aparece la opción de `formatear código` ![image](https://user-images.githubusercontent.com/11671943/84305089-d430c500-ab2f-11ea-838b-825b1fb2eeae.png).

Esto aunque no es ideal, es intencional; implementar el formateo con multiples editores no es tan trivial. Queda como algo para el futuro cuando tengamos un mejor sistema de formato.
