### ISSUE TITLE
Immersive redirection

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-laboratory#1489]
It was very cumbersome to explain it in prose, so some code is presented instead.
Note: all presented code is just pseudo-code with the exception of `student_granted_organizations`. :stuck_out_tongue: 

When accessing to a link in this app the behavior should be:

`immersive_organizations  = student_granted_organizations.select(&:immerse_in_current_organization?)`

- If immersive_organizations.present?: 
   - If accessing to a content:
       `better_immersive_organizations = immersive_organizations.select(&:has_that_content?)`

       - If `better_immersive_organizations.present?`, the redirection should be to `better_immersive_organizations.pick_one` to that same content without any pop-up.
       - else: redirect it to `immersive_organizations.pick_one`. In this case the redirection should be to the main page of that organization (book page) with a pop-up shown upon landing with text that is yet to be defined. _*1_ 
   - If accessing to a forum route (/discussions): same behavior as *1 but with a different pop-up with text yet to be defined.
   - Any other route: Redirect to that same route in `immersive_organizations.pick_one` without any pop-up.
    
- else: no redirection whatsoever for now.

Note 2: When I'm referring to content it means to that exact piece of content (same topic, guide or exercise).
Note 3: pick_one means that if there is more than one, let's make it choose from a pop-up (organization_chooser). If not, let's use that one organization as target.

**Comment by flbulgarelli** [comment]
Great!

> Redirect it to the last organization which is immersive for the current one that has that specific content. In this case the redirection should be to that content but with the new selected organization.

When you say _last organization_ do you mean the most recently created organization, or the organization that has been more recently added to the user permissions? I think it is the second option, but we should take into account that permissions don't record when the grant has been added, so using the permissions order may not be that reliable. Nevertheless, having more than one immersive organization is uncommon,

**Comment by faloi** [comment]
Just for documentation purposes, these are the routes I found by running `rails app:routes`:

```rb
# Content
/:tenant/chapters
/:tenant/exercises
/:tenant/guides
/:tenant/lessons
/:tenant/complements
/:tenant/exams
/:tenant/topics

# Interaction
/:tenant/discussions
/:tenant/messages

# User settings
/:tenant/user
/:tenant/join

# API
/:tenant/api
```

**Comment by faloi** [comment]
@luchotc please review the following pseudo-implementation:

```ruby
def redirect!
    immersive_organizations = student_granted_organizations.select(&:immerse_in_current_organization?)
    return unless immersive_organizations.present? # no immersive orgas, no redirection

    if is_content?
        orgas_with_content = immersive_organizations.select(&:has_that_content?)
        redirect_to orgas_with_content.pick_one.route_for_content unless orgas_with_content.empty?

        # In this case the redirection should be to the main page of that organization (book page) with a pop-up shown upon landing with text that is yet to be defined. (#1) 
        redirect_to immersive_organizations.pick_one.main_page(show_redirect_text: true)
    end 

    if is_discussion?
        redirect_to immersive_organizations.pick_one.discussions_main_page(show_redirect_text: true)
    end

    redirect_to immersive_organizations.pick_one.route_for path
end
```

**Comment by luchotc** [comment]
Perfect :100:

**Comment by faloi** [comment]
There is one case that I think could be wrong. 

Suppose you are registered in an immersive orga that only has Gobstones content, and you want to take a look at some other content (name Haskell) in a public-immersible orga. Our algorithm will automatically redirect you to the Gobstones orga main page.

**Comment by faloi** [comment]
@luchotc also, another one: if I don't get it wrong, discussions are created on a per-exercise fashion, and in that case it would be useful to redirect the user to the discussion of the same exercise in its orga.

**Comment by luchotc** [comment]
> There is one case that I think could be wrong.
Suppose you are registered in an immersive orga that only has Gobstones content, and you want to take a look at some other content (name Haskell) in a public-immersible orga. Our algorithm will automatically redirect you to the Gobstones orga main page.

We've consider it and we can live with it. The tendency will be to create reduced specific organizations as public immersible and that wouldn't be a problem. Future work is to add tags to organizations or take them from content tags and decide what kind of content is each organization offering and take in into consideration along with the target audience. But it's ok for now.

> @luchotc also, another one: if I don't get it wrong, discussions are created on a per-exercise fashion, and in that case it would be useful to redirect the user to the discussion of the same exercise in its orga.

We can definitely take this into account. I simplified it so it is easier, but if you can consider it without much extra work it would be great. Usually external links that are shared are for an specific discussion, and we can't do much about it.

**Comment by faloi** [comment]
@luchotc any ideas to improve this dialog?

![image](https://user-images.githubusercontent.com/1585835/98382029-6a0e4480-2029-11eb-9ca0-307bdcdd5ec8.png)
