### ISSUE TITLE
En primer ciclo las vestimentas se tienen que cargar antes 

### ISSUE THREAD

**Issue by rgonzalezt** [mumuki/mumuki-laboratory#1506]
Si las vestimentas no se cargan del todo antes de comenzar a ejecutarse el ejercicio, no se llegan a ver las vestimentas la primera vez que se ejecuta el ejercicio. **Esto hace que no se entienda del todo lo que está pasando en el tablero afectando al estudiante en su aprendizaje.**

**Comment by flbulgarelli** [comment]
¿Este issue lo resuelve https://github.com/mumuki/mumuki-gobstones-runner/pull/217?

**Comment by luchotc** [comment]
:point_up:
