### ISSUE TITLE
Mumuki no responde

### ISSUE THREAD

**Issue by Yivo4** [mumuki/mumuki-laboratory#1522]
Trate de entrar a la pagina de mumuki  https://mumuki.io/primeros-pasos/ , y la pagina indica que hubo un error.

**Comment by flbulgarelli** [comment]
¡Hola! ¿Que error te muestra? ¿Podrías adjuntar el mensaje o una captura de pantalla?

**Comment by julian-berbel** [comment]
Hola! hallamos y arreglamos un error que impedía que a usuarios con ciertos permisos les cargara bien la página.
Si seguís experimentando problemas podés reabrir este issue!

**Comment by Yivo4** [comment]
Muchas gracias.
