### ISSUE TITLE
Runners should be able to provide contextualization status translations

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-laboratory#1536]
As a request of @Gustrucco, it would be desirable that at least success messages can be overridden by runners. 
Nowadays we have different messages between kindergarten and the other layouts. We should also allow runners to provide a custom message which supersedes them.

It would also be nice to create another file for inputs overwrites, and instead of doing this: https://github.com/mumuki/mumuki-laboratory/blob/master/app/helpers/contextualization_result_helper.rb#L24 we always look for #{input_type}.#{status} and default to status if it doesn't exists, to make it more extensible and clear.

**Comment by fedescarpa** [comment]
Closed in #1538
