### ISSUE TITLE
Borrado de mensajes del foro

### ISSUE THREAD

**Issue by rgonzalezt** [mumuki/mumuki-laboratory#1568]
Cuando se borran los mensajes del foro, no es fácil recuperarlos. Esto es un problema porque:
- Si hubo insultos o pasaron soluciones, deben borrarse inmediatamente. De esta manera, nos quedamos sin esos mensajes como pruebas para presentar.
- Si alguien pasa información sensible, otra persona lo ve y se queja pero ese mensaje lo borra quien lo originó (sin que llegan a verlo les mentores), nos quedamos sin ese mensaje para corroborarlo.

Actualmente lo que estamos haciendo para los primeros casos es sacar una captura de pantalla del mensaje antes de borrarlo.

Debido a estos problemas, estaría bueno que esos mensajes que se quieren eliminar en realidad se **oculten** para, por lo menos, les estudiantes. Es decir, que sólo puedan verlos les mentores (o quizás sólo les admins) una vez "eliminados" estos mensajes.

**Comment by flbulgarelli** [comment]
@luchotc let's discuss this issue ASAP.

**Comment by luchotc** [comment]
This one is being addressed by @felipecalvo but including the reason for message deletion and with the possibility of hiding it completely or leaving a message like Whatsapp does saying "this message was deleted because #{reason}" :smile:

**Comment by felipecalvo** [comment]
This is taking a while to be deployed for external reasons but is already done at https://github.com/mumuki/mumuki-laboratory/pull/1606 -  we'll finally have it on production this week! :raised_hands:
