### ISSUE TITLE
Exercise passed but not actually passed after refreshing

### ISSUE THREAD

**Issue by felipecalvo** [mumuki/mumuki-laboratory#1585]
I'm not sure what caused this. I was testing with another user and created a new one. Then, after sending the solution, which seemed to be cached (it was processed instantly) I got seven times the exp I should have.

![image](https://user-images.githubusercontent.com/11304439/110394270-ea31ce80-804a-11eb-9a32-287317302d13.png)

Then, when I went back to the previous exercise, it didn't show as completed at all - it was not green and the solution was empty.

I believe this is related to https://github.com/mumuki/mumuki-laboratory/issues/1576? Seems like it's an issue with cache ~as almost everything that troubles us~

**Comment by luchotc** [comment]
I'm 99% sure that the cache is involved. The only thing I can't explain is that 700 :confused:

**Comment by luchotc** [comment]
The cache part should be resolved now with https://github.com/mumuki/mumuki-laboratory/pull/1593

**Comment by felipecalvo** [comment]
It's probably all part of the same problem. I'll close for now.
