### ISSUE TITLE
'Your solution has changed' warning pops up always on read only mode

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mumuki-laboratory#1682]
(Even when solution has not changed)

https://user-images.githubusercontent.com/11720274/133646614-f1055292-ee9d-436e-8ccf-dac8ca932ed2.mp4

**Comment by julian-berbel** [comment]
This issue still occurs on choice exercises

**Comment by julian-berbel** [comment]
This also occurs on gobstones jr!!

**Comment by flbulgarelli** [comment]
> This issue still occurs on choice exercises

Too bad :cry:. This is something we must fix ASAP
