### ISSUE TITLE
reporte de error - Modulo Nivelacion Python - Fundamentos de Python

### ISSUE THREAD

**Issue by MaelaLombardi** [mumuki/mumuki-laboratory#1717]
Buenos días,
Les envío los errores que arrojó la plataforma mumuki en el primer módulo de Python:

Error 500 en las pantallas 4 (strings) y 5 (concatenar strings)
Error en la consola de los ejercicios cuando se ingresa información. 
Les copio aquí abajo el error que arroja primero, luego es posible escribir pero pareciera que no queda grabado lo que se ingresa porque no arroja resultados cuando se hacen las acciones solicitadas (print, calculos matematicos, etc).

<!DOCTYPE html>
<html lang="es">
<head>
<title>Prework de Data Science</title>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<meta name="description" content="Curso de Digital House Data Science"/>

<meta property="og:site_name" content="Curso de Digital House Data Science" />
<meta property="og:title" content="Prework de Data Science"/>
<meta property="og:description" content="Curso de Digital House Data Science"/>
<meta property="og:type" content="website"/>
<meta property="og:image" content="https://mumuki.io/static/logo-digitalhouse.png"/>
<meta property="og:url" content="https://mumuki.io/data-science.digitalhouse/exercises/5967-nivelacion-python-fundamentos-python-tipos-de-division/queries"/>

<meta name="turbolinks-cache-control" content="no-cache">

<link rel="stylesheet" media="all" href="/assets/academia-db06762bb5c917abc238f175366712a91badc67741a3f9826370d4fb801a74f4.css" data-turbolinks-track="reload" />
<script src="/assets/academia-2556e5845d597063d67587cd91c2d8d082bc052c40d18bf3a21e1abd98fafe7b.js" data-turbolinks-track="reload"></script>

<link rel="icon" type="image/x-icon" href="https://www.digitalhouse.com/wp-content/themes/dh/assets/img/icons/favicon-32x32.png" data-turbolinks-track="reload">
<link rel="stylesheet" type="text/css" href="https://mumuki.io/data-science.digitalhouse/theme_stylesheet" data-turbolinks-track="reload">
<script type="text/javascript" src="https://mumuki.io/data-science.digitalhouse/extension_javascript" defer data-turbolinks-track="reload"></script>

<meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="P9kbTv6KT2/RRbWxyhU2b8/GNA4dg9wyL0UOpnfPRGIiFBEQOf+pNZYES3fGT9+sh4YW4m6C7AifCEx/+fJ02Q==" />

<script type="text/javascript">
window.mumukiLocale = {"facebook_code":"es_LA","auth0_code":"es","name":"Español"};
mumuki.locale = 'es';
moment.locale('es');

mumuki.incognitoUser = false;

mumuki.version = '9.21.0';
</script>

<script src="https://cdn.auth0.com/js/lock/11.5.2/lock.min.js"></script>

</head>
<body>

<input type="hidden" name="mu-user-id" id="mu-user-id" value="418838" />
<input type="hidden" name="mu-organization-id" id="mu-organization-id" value="495" />

<div class="mu-read-only">
<small>Estás en Modo Lectura: como el curso ya finalizó no podrás enviar soluciones</small>
</div>

<div class="container px-0">
<nav class="navbar navbar-light navbar-expand-lg mu-navbar">
<div class="container-fluid">
<button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#muNavbar" aria-controls="muNavbar" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="mu-navbar-avatar order-lg-2">
<div class="dropdown mu-navbar-element notifications-box d-none">
<div id="notificationsDropdown" class="profile-dropdown" data-bs-toggle="dropdown" aria-label="Notificaciones" role="menu" tabindex="0">
<i class="fas fa-bell fa-fw fa-2x mu-navbar-icon"></i>
<span class="badge badge-notifications">0</span>
</div>
<ul id="notificationsPanel" class="dropdown-menu dropdown-menu-end" aria-labelledby="notificationsDropdown">
</ul>
</div>

<div class="dropdown mu-navbar-element">
<div id="profileDropdown" class="profile-dropdown dropdown-toggle" data-bs-toggle="dropdown" aria-label="Usuario" role="menu" tabindex="0">
<img height="40" onError="this.onerror = null; this.src = &#39;https://mumuki.io/assets/user_shape-636f9cd452aa3bed9fe3372d73eea31381394b17017f189391628673d0b99333.png&#39;" class="rounded-circle " src="https://mumuki.io/assets/avatars/grown_ups/bulb_default-0f51ce17767f5109e7070de71e4f8f8340d03b784a7a252beb87d329788db5df.png" alt="Bulb default" />
</div>
<ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profileDropdown">
<li><a role="menuitem" tabindex="-1" class="dropdown-item " href="/data-science.digitalhouse/user"><i class="fas fa-user fa-fw fixed-icon"></i><span class="fa5-text">Mi cuenta</span></a></li>
<li class="dropdown-divider"></li>

<li><a role="menuitem" tabindex="-1" class="dropdown-item " href="/logout?organization=data-science.digitalhouse&amp;origin=%2Fdata-science.digitalhouse%2Fexercises%2F5967-nivelacion-python-fundamentos-python-tipos-de-division%2Fqueries"><i class="fas fa-sign-out-alt fa-fw fixed-icon"></i><span class="fa5-text">Cerrar Sesión</span></a></li>
</ul>
</div>
</div>
<div class="collapse navbar-collapse mu-navbar-breadcrumb-container" id="muNavbar">
<div class="mu-navbar-breadcrumb order-lg-1">
<ul class="navbar-nav mu-breadcrumb-list">

<li class='mu-breadcrumb-list-item brand'><a href="/paths"><i class='da da-mumuki' aria-label=Inicio></i></a></li>

</ul>
</div>
</div>
</div>
</nav>
</div>

<div class="toast-container bottom-0 start-0 p-3">

</div>

<div class="container mb-5" id="wrap">

<div class="error-message">

<div class="header">
<img class="error-code-img" src="/error/410.svg">
</div>
<div class="body">
<h2>¡Ups! El contenido expiró</h2>
<p class="mu-error-status-line">
Esto es lo que se conoce como <span class="error-link"><a href='https://es.wikipedia.org/wiki/Anexo:C%C3%B3digos_de_estado_HTTP' target='_blank'> error 410 </a></span>.
</p>
<p class="mu-error-explanation-line">
Este recorrido ha finalizado
</p>
</div>

</div>

</div>

<footer class="footer">
<div class="mu-footer container">
<div class="mu-footer-row">
<div class="mu-footer-authoring">

</div>
</div>

<div class="mu-footer-row">
<div class="mu-footer-copyright">
&copy; 2015-2021
<a href="http://mumuki.org/" class="mu-org-link"><span class="da da-mumuki-circle"></span> Mumuki</a>

</div>

<div class="mu-footer-terms">
<div></div>
<div><a target="_blank" href="/data-science.digitalhouse/user/terms">Términos y Condiciones</a></div>
</div>

<div class="mu-footer-login-provider">
<a href="https://auth0.com/" target="_blank">
<img height="40" alt="JWT Auth for open source projects" src="//cdn.auth0.com/oss/badges/a0-badge-light.png"/>
</a>
</div>

<div id="footer-social" class="mu-footer-social" lang="en">
<a class="fab fa-instagram social-icon" aria-label="Instagram" href="https://www.instagram.com/mumukiorg" target="_blank"></a>
<a class="fab fa-twitter social-icon" aria-label="Twitter" href="https://twitter.com/MumukiOrg" target="_blank"></a>
<a class="fab fa-youtube social-icon" aria-label="Youtube" href="https://www.youtube.com/c/MumukiOrg" target="_blank"></a>
<a class="fab fa-github social-icon" aria-label="Github" href="https://github.com/mumuki" target="_blank"></a>

</div>
</div>

</div>
</footer>

</body>
</html>

**Comment by MaelaLombardi** [comment]
Buenos días, les agrego otras pantallas que dan el mismo error 500 que no permiten ver el contenido: 
Modulo: Nivelación Python
Lección 2: listas, diccionarios, tuplas
Ejercicios: 5 (método append), 9 (actualizando diccionarios)

Lección: 3: bucle for
Ejercicios: 1 (iteracion I)

**Comment by flbulgarelli** [comment]
¡Buenas!

Para consultas relativas al contenido o la plataforma mumuki.io, contactar por favor a la persona administradora de tu organización. 

¡Saludos!
