### ISSUE TITLE
Mongo runner?

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#249]
Perhaps implementing a runner for running and testing Mongo queries could be not-too-difficult, and open to a broader audience.

Yeah, I know, we already have a lot of work here, but perhaps it @jzaffaroni could find awesome use-cases for it :smile:

**Comment by flbulgarelli** [comment]
@faloi @fedescarpa

**Comment by faloi** [comment]
Could be interesting, but I would do it if and only if @jzaffaroni creates exercises

**Comment by jzaffaroni** [comment]
Ok.
I like it

Enviado desde mi iPhone

**Comment by flbulgarelli** [comment]
Not in current roadmap. Closing.
