### ISSUE TITLE
Proof assistant runner?

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-laboratory#324]
Given a grammar, like [PCF](http://www.wikiwand.com/en/Programming_Computable_Functions): 

![image](https://cloud.githubusercontent.com/assets/1585835/10080475/38152bcc-62c6-11e5-8fee-25de18f941bb.png)

...and a set of rules, like _call by name_ reduction...

![image](https://cloud.githubusercontent.com/assets/1585835/10080484/4b169ba2-62c6-11e5-9190-0f1993d75577.png)

...I want the runner to validate this demonstration is ok:

![image](https://cloud.githubusercontent.com/assets/1585835/10080456/1793c660-62c6-11e5-9633-bde9cb0d881b.png)

Perhaps we could use [Agda](http://www.wikiwand.com/en/Agda_%28programming_language%29) or even Haskell.

**Comment by flbulgarelli** [comment]
Motivation? Do we have any potential user for this?

**Comment by flbulgarelli** [comment]
Closing. Please reopen if there is any real user for this runner.
