### ISSUE TITLE
Extract css bower component

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-laboratory#437]
Whe should have a repo only of styles, so as to be consistent in all platforms

**Comment by faloi** [comment]
Isn't this done by now? @fedescarpa

**Comment by aguspina** [comment]
Yup

**Comment by flbulgarelli** [comment]
Hmm, but, but...this has not being integrated in atheneum yet. We just have the repo with some styles, but atheneum is not using them.

**Comment by faloi** [comment]
Let's change the issue title then.

**Comment by faloi** [comment]
I don't know if a bower/npm package could be included in a Rails project... perhaps we also need to create a gem?

**Comment by flbulgarelli** [comment]
@faloi  yes, we can include it. We are already including many bower components through https://rails-assets.org/


I have just index it, It will be available in a few minutes

**Comment by flbulgarelli** [comment]
https://rails-assets.org/#/components/mumuki-styles

**Comment by flbulgarelli** [comment]
Renaming and closing issue, since the extract-generic-css has already  being done through mumukit-styles, and there is already a new issue for integrating into this repository #749
