### ISSUE TITLE
I can only write numbers in the console from mobile

### ISSUE THREAD

**Issue by mmatos** [mumuki/mumuki-laboratory#486]
As the title says, only numeric characters go through in the console when using my phone. I was doing a playground exercise, and not only could I not type, I can't paste copied code to test it either, so I had no choice but skip it.

**Comment by flbulgarelli** [comment]
Won't fix. This is a long standing ACE editor bug - https://github.com/mumuki/mumuki-laboratory/issues/487 -, and there are no plans to change it in the near future.
