### ISSUE TITLE
Shift key behaves as backspace on mobile

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-laboratory#487]
Happened to me on my Nexus 7 tablet, running  Android 6.0.1.

Perhaps it's an Ace bug, but makes Atheneum unusable. :cry:

**Comment by faloi** [comment]
It's an Ace bug: https://github.com/ajaxorg/ace/issues/2038

**Comment by faloi** [comment]
Still an issue, but not related to our project. Closing.

**Comment by flbulgarelli** [comment]
Reopening since now we are planning to migrate to CodeMirror
