### ISSUE TITLE
Adding comments in the code messes up the inspections validation

### ISSUE THREAD

**Issue by mmatos** [mumuki/mumuki-laboratory#501]
Weird bug, I'm adding screenshots so you can see I'm not lying.

Comment before the function to validate => HasUsage:foldl1 inspection passes.
![image](https://cloud.githubusercontent.com/assets/715971/14604748/8be4a174-054b-11e6-822a-048a986d3666.png)

Comment after the function to validate => HasUsage:foldl1 inspection fails.
![image](https://cloud.githubusercontent.com/assets/715971/14604801/c9e5b9a4-054b-11e6-93f5-eba1e888d7ef.png)

**Comment by mmatos** [comment]
Another example
![image](https://cloud.githubusercontent.com/assets/715971/14604868/20726bbe-054c-11e6-8b99-1f828d26a1b1.png)

**Comment by flbulgarelli** [comment]
Hehe, it seems you have done Sql Injection :stuck_out_tongue:

**Comment by flbulgarelli** [comment]
Just kidding, it is a bug in the Haskell runner. There must be a missing `\n'

**Comment by flbulgarelli** [comment]
Fixed in https://github.com/mumuki/mumuki-laboratory/pull/779
