### ISSUE TITLE
Allow sending answers using keyboard shortcuts

### ISSUE THREAD

**Issue by nicosantangelo** [mumuki/mumuki-laboratory#527]
It could be useful to be able to press a keyboard shortcut like `ctrl+enter/cmd+enter` when writing on the editor `textarea` to submit the answer instead to having to use the mouse.

The usefulness also resides in the fact that the common way of jumping between inputs, pressing `tab`, is used inside the `textarea`.

**Comment by luchotc** [comment]
Closing as it's already implemented now
