### ISSUE TITLE
Send issues to a GH repo instead of sending an email

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-laboratory#573]
Definitively the email mechanism is not enough: we currently so many mails we can't process or delegate to someone else.

I'm proposing to move the error reports to GitHub issues, so we can take advantage of its benefits:
- we could pick an assignee, avoiding duplicate work;
- all the issues would be centralized in the same place;
- fill a form to report an issue it's easier tan sending an email.

To do so, the `mailto:` link should be replaced with a popup form that ends up creating an issue on some repo.

**Comment by faloi** [comment]
@fedescarpa @flbulgarelli @aguspina please comment.

Regarding the repo, I have two ideas:

1. Send every issue to the same repo. 
2. Send each issue to its guide's repo.

**Comment by fedescarpa** [comment]
OMFG! That's a great idea!

**Comment by aguspina** [comment]
Agree

**Comment by flbulgarelli** [comment]
Could that be configurable per organization? Or have both? I am not sure, I _feel_ I still need the contact email in some cases.

**Comment by faloi** [comment]
Ok, but which option do you choose? I think the centralized repo should be
better, but I'd like to hear your thoughts.

**Comment by faloi** [comment]
The development should be guided by facts, not feelings. :P

I agree that a downside of moving to GH is the potential lack of an email
to speak with the student. Another one is privacy: it should be clear to
the user that what she's sending would be public... unless we create a
private repo.

**Comment by faloi** [comment]
I'd like to go on with this. Can we decide?

**Comment by fedescarpa** [comment]
@faloi, I'm agree with you

**Comment by faloi** [comment]
But we have to decide between these options:

1. Send every issue to the same repo.
2. Send each issue to its guide's repo.

I'm with number 1, perhaps configurable by organization.

**Comment by chrisgel15** [comment]
Hi, I am solving all exercises and finding some issues or enhacements in a couple of them. Sent an email but then I found this repo. Where should I redirect all my questions?

Thx

**Comment by flbulgarelli** [comment]
> Hi, I am solving all exercises and finding some issues or enhacements in a couple of them. Sent an email but then I found this repo. Where should I redirect all my questions?

Oops, a bit late but yes, you can post issues here or send them to issues@mumuki.org.

**Comment by flbulgarelli** [comment]
Also, closing this issue. Adding this feature is not that necessary anymore, since now the platform is quite more stable than 2 years ago.
