### ISSUE TITLE
Exam timer UI is a bit ugly

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#576]
See: 

![exam](https://cloud.githubusercontent.com/assets/677436/15483995/191b32e6-210e-11e6-8cb9-aff8c5916b04.png)

 The timer requires two lines. It is also misspelled: _te queda una hora y 23 minutos_. And there is _a lot_ of whitespace - it is really disturbing.

**Comment by luchotc** [comment]
Closing it as it takes only one line now
