### ISSUE TITLE
students skip the corollary

### ISSUE THREAD

**Issue by MagdalenaMileto** [mumuki/mumuki-laboratory#631]
It would be nice to force the student to read it, disabling the `next` button for 10 seconds in exercises and guides.

**Comment by flbulgarelli** [comment]
@faloi what do you think?

**Comment by faloi** [comment]
It's true, students usually don't read it. But forcing a 10 seconds timer seems too agressive to me... perhaps this is one of the things that should be enforced by the teacher at the classroom and there is nothing we can do to automate it.

**Comment by flbulgarelli** [comment]
Perhaps we could remove the title "Para pensar", and put the text out of the corollary. 

![photo4925062406351202254](https://user-images.githubusercontent.com/677436/29139931-0a5ea620-7d1f-11e7-89b1-00828cb62eff.jpg)

vs

![photo4925062406351202255](https://user-images.githubusercontent.com/677436/29139934-0c0be546-7d1f-11e7-8c92-f079f5805ebc.jpg)

**Comment by flbulgarelli** [comment]
Closing until we have more evidence that this is actually an issue.
