### ISSUE TITLE
Remove solution success rate and exercise success rate

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-laboratory#700]
Perhaps we can replace it by "Solutions sent" and "Exercises solved", metrics that are more interesting and don't go against our philosophy (I believe success rate DOES go against what we think about errors).

**Comment by faloi** [comment]
@flbulgarelli please comment.

**Comment by flbulgarelli** [comment]
I agree.

**Comment by flbulgarelli** [comment]
We have removed such status some months ago. Closing.
