### ISSUE TITLE
Allow students to reset their lesson submissions

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#704]
A lot of times students solve lessons, and a few months later -  because final exams - they want to solve those lessons again. 

This situation also occurs when they are students again of the same subject, and teacher want's them to re-do exercises. Or simply, when they want to re-do exercises as a in a code-cata - I actually recommend solving exercises many times, in different ways, ignoring the original solution. 

Some of those students have proposed adding a _reset lesson_ or _reset chapter_  feature, which could address this problem.

**Comment by flbulgarelli** [comment]
@estefaniamiguel @faloi?

**Comment by faloi** [comment]
Agree, the voice of the students is far more powerful than my opinion. Nevertheless, in a further iteration I'd like to think a way to explicitly show this on classroom.

**Comment by flbulgarelli** [comment]
We could keep this option configurable as a organization property, though.

**Comment by faloi** [comment]
I don't think that's necessary, after all no data would be lost. If
possible, I'd like to store the reset date somewhere, just in case we
decide to display it somewhere in classroom.

**Comment by flbulgarelli** [comment]
Fixed by https://github.com/mumuki/mumuki-platform/issues/297
