### ISSUE TITLE
Lessons order do not match what their urls say

### ISSUE THREAD

**Issue by mdumrauf** [mumuki/mumuki-laboratory#707]
Examples:

- "1. Primeros Programas" => you can read a **27** in the URL http://mumuki.io/lessons/27-fundamentos-primeros-programas
- "Capítulo 1: Fundamentos" => you can read a **6** in the URL http://mumuki.io/chapters/6-fundamentos

And so on.

**Comment by flbulgarelli** [comment]
This is not an issue right now. Pure URL-based navigation is not a design goal.
