### ISSUE TITLE
cambiar el link de  ¿Pensás que algo está mal con este ejercicio?

### ISSUE THREAD

**Issue by jesuslombardo** [mumuki/mumuki-laboratory#728]
Esto nos aliviaría mucho el trabajo día a día, los cambios serían pocos:
Cambiar el texto del link actual, porque se ve como algo más técnico y específico, cuando en realidad, es pedir ayuda porque no sabes como avanzar. Les parece poner algo así como: "¿Te trabaste?, Te ayudamos acá
Por otro lado, en la unidad de Fundamentos no llegué a ver este link implementado se podría agregar también??
El subject del Mail que nos envía, nos informe de alguna forma que unidad está, si puede ser todo mejor, tipo 1.10.5 (Fundamentos, Igualmente Conectados, El informe)
Finalmente darle un formato al link más cómo un botón, para que sea bien visible, esto lo dejamos a su criterio si están de acuerdo.

Como siempre gracias!!! y esto nos va ayudar mucho a agilizar los tiempos y las consultas!!

**Comment by flbulgarelli** [comment]
Hola!

El objetivo del link es justamente técnico y específico: está pensado para avisar cuando el enunciado está mal redactado, o tiene un tipo, o los tests están rotos.

Para lo que vos querés, Jesús, habrá una nueva funcionalidad pronto, llamada levantar la mano, que registrará y notificará pedidos de ayuda y se integrará con classroom, permitiéndo responder cada duda  desde la aplicación. 

Está planificada para mediados/fines de abril.
