### ISSUE TITLE
AGREGAR BIBLIOTECA EN TODOS LOS EJERCICIOS QUE LO REQUIERA

### ISSUE THREAD

**Issue by jesuslombardo** [mumuki/mumuki-laboratory#729]
En todos los ejercicios que requiera una función predefinida, agregar la solapa Biblioteca, así queda más unificado y más claro en todos los ejercicios ese concepto!

**Comment by flbulgarelli** [comment]
Resuelto en todos los ejercicios de Gobstones!

**Comment by flbulgarelli** [comment]
De ahora en más, reportar este tipo de issues en github.com/mumukiproject/mumuki-contenido/issues
