### ISSUE TITLE
Use mumuki-styles

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#749]
We need to use mumuki-styles. 

I have tried it in https://github.com/mumuki/mumuki-laboratory/tree/feature-generic-ui, with no success.

Although css is imported properly, JS is not working.

**Comment by fedescarpa** [comment]
I create a README.md file in [mumuki-styles](https://github.com/mumuki/mumuki-styles)

Take a look to it, I think you are missing to add some required code.

![bitmoji](https://render.bitstrips.com/v2/cpanel/10216108-170770054_3-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by flbulgarelli** [comment]
yup, I have followed it.

**Comment by flbulgarelli** [comment]
The problem was with  `jquey` version. `styles`  is requiring a newer version that breaks the `on('ready')` event.
