### ISSUE TITLE
Save last exercise and submission date discriminated by organization

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#751]
Now, laboratory is saving only the last submissions globally. It would be nice to save it by organization, so that going to last exercise works even if you are logged into more than one organization.

**Comment by flbulgarelli** [comment]
@aguspina suggest that we could solve this by making submissions organization-aware.

**Comment by luchotc** [comment]
Closed as we are going to use one assignment per organization
