### ISSUE TITLE
No funciona el link

### ISSUE THREAD

**Issue by Alekin13** [mumuki/mumuki-laboratory#771]

**Comment by flbulgarelli** [comment]
¡Hola!

¿A qué link te referís?

**Comment by Alekin13** [comment]
Hola Franco

El link que no funciona es pdep-utn.mumuki.io no se si habrá cambiado. Pero
necesitaría poder ingresar en los próximos días.

Saludos

2017-03-15 23:13 GMT-03:00 Franco Leonardo Bulgarelli <
notifications@github.com>:

**Comment by flbulgarelli** [comment]
Hola!

La organización pdep-utn se encuentra fuera de servicio. Consultá a tu docente por favor.

**Comment by Alekin13** [comment]
Hola,
Primero.. ya firmé la materia a fines del 2015. Y segundo ud fue el
docente. Yo quiero acceder para empezar a preparar el final. No importa si
es pdep-utn. Tiene algún link de acceso disponible donde haya ejercicios
básicos para recordar los conceptos de los paradigmas incluyendo objetos?
Desde ya gracias

Saludos

**Comment by flbulgarelli** [comment]
Hola!

En mumuki.io (a secas) hay bastante material que puede servirte. Sobre el paradigma de objetos (aún) no hay nada.

Saludos!
