### ISSUE TITLE
Wrong link to classroom

### ISSUE THREAD

**Issue by estefaniamiguel** [mumuki/mumuki-laboratory#772]
On http://algo2-undav.mumuki.io/ if I enter with my user (a teacher user).
When displaying the options on my profile and clicking on Classroom (Aula in spanish) it takes me to http://organization.classroom.mumuki.io/#/courses.
But that is not a real classroom. My classroom is:
http://algo2-undav.classroom.mumuki.io/#/courses.

**Comment by aguspina** [comment]
Fixed via 0de06507fc4cd4c3cef0f3eb6a383125e0a41cfd
