### ISSUE TITLE
Wrong permission or maybe link should not show up

### ISSUE THREAD

**Issue by estefaniamiguel** [mumuki/mumuki-laboratory#773]
On http://algo2-undav.mumuki.io/ if I enter with my user (a teacher user).
When displaying the options on my profile and clicking on Office (Secretaría in spanish) it takes me to http://office.mumuki.io/.
And there I can modify a lot of things (haven't done that but the option is there)

**Comment by flbulgarelli** [comment]
If you try to do any action, it will fail since you have not the right permissions. 

But it is true that the link should not even appear.

**Comment by estefaniamiguel** [comment]
According to @aguspina I have Bedel permissions so it should show up.
But the problem now is that I can go to an edit view but when editing I go to a page that shows this error:
"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

**Comment by luchotc** [comment]
This is fixed now
