### ISSUE TITLE
Los mensajes de error al enviar una solución no son suficientemente explicativos

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-laboratory#801]
Cuando la solución no compila responde:
`Ups tu solución no funcionó`... propongo: `Ups, tu solución no se pudo ejecutar`

Cuando la solución no pasa los tests responde:
`Ups, algo no anduvo bien`... propongo: `Ups, tu solución no resuelve el problema`

¿Qué opinan @asanzo @flbulgarelli @fedescarpa @lauramangifesta @arielumansky @faloi?

**Comment by faloi** [comment]
`Ups, tu solución no se pudo ejecutar`

Me gusta, aunque habría que asegurarse de que las guías hablen de "ejecutar" las suficientes veces como para que quede claro qué significa.

`Ups, tu solución no resuelve el problema`

Esta me hace un poco más de ruido, me parece demasiado fuerte la afirmación. Lo que sí noté es que a los pibes los marea un poco que el error sea una afirmación que ellos tienen que negar.

Por ejemplo si falla un test llamado "Pepita cambia de ciudad cuando vuela", lo que ellos tienen que entender es que eso falló porque "Pepita NO cambia de ciudad cuando vuela". Una idea que se me ocurre así al vuelo es darle apariencia de check list, que quizás es algo más cotidiano:

:white_check_mark: ~~Pepita está definida~~
:white_check_mark: ~~Pepita entiende volar hacia~~
:x: Pepita cambia de ciudad cuando vuela

**Comment by lauramangifesta** [comment]
Coincido con Fede en tres cosas:
1) Me gusta el "tu solución no se pudo ejecutar" AUNQUE da lugar a que
parezca un error nuestro, del servidor o algo así, y no un error del
alumno. Suena a "nosotros no pudimos ejecutarlo".
2) Suena bastante fuerte el "tu solución no resuelve el problema". Se me
ocurre, quizás: "Ups, parece que tu solución tiene errores"
3) A veces no se entiende qué anduvo mal cuando tira una afirmación.
Tampoco se entiende en el caso de booleanos que tira "true=false" y no
sabés si tu solución da true o si debería dar true y da false.



2017-07-24 12:36 GMT-03:00 Federico Aloi <notifications@github.com>:

**Comment by flbulgarelli** [comment]
¿Que tal usar diferentes colores e iconos? Por ejemplo, podríamos incorporar un nuevo color `broken`: 

![screencapture-smartedu-mumuki-io-exercises-3394-objetos-con-tipado-estatico-practica-polimorfismo-panza-llena-corazon-contento-1502397816008](https://user-images.githubusercontent.com/677436/29191465-316ac976-7df4-11e7-9e88-18312253056d.png)

**Comment by flbulgarelli** [comment]
> 2) Suena bastante fuerte el "tu solución no resuelve el problema". Se me
ocurre, quizás: "Ups, parece que tu solución tiene errores"

> Ups, tu solución no resuelve el problema
> Esta me hace un poco más de ruido, me parece demasiado fuerte la afirmación. 
¿Qué tal así?

* No se pudo ejecutar (con icono de prohibido) (rojo oscuro)
* No pasó las pruebas (con icono de cruz) (rojo claro)
* Hay cosas para mejorar (con warning) (amarillo)
* Pasó todas las pruebas (tilde) (verde)
