### ISSUE TITLE
Ruby icon is not rendering on certain excercise

### ISSUE THREAD

**Issue by Charlyzzz** [mumuki/mumuki-laboratory#803]
Proofs attached below:

![image](https://user-images.githubusercontent.com/7073356/29008468-ebf7fe6c-7aed-11e7-959d-a8fa0e73680c.png)
![image](https://user-images.githubusercontent.com/7073356/29008470-eff2f562-7aed-11e7-8ab2-e9e27460492f.png)

**Comment by flbulgarelli** [comment]
Hi! This is not a bug - it just happens that the icon references the kind of evaluation. In this case, it is _text_, not _ruby_. 

Perhaps we could display a choice icon in this case, like http://fontawesome.io/icon/list-ol/ or http://fontawesome.io/icon/check-square-o/
