### ISSUE TITLE
Puse una formula que me parecio correcta.

### ISSUE THREAD

**Issue by juanmafx** [mumuki/mumuki-laboratory#808]
Como que quedo roto el link.
A pesar de actualizar.

Aun no probe cerrar secion y entrar de nuevo

**Comment by flbulgarelli** [comment]
¡Hola! Gracias por comentar. 

Si pensás que hay algo que no funciona en la plataforma, tratá por favor de explicarnos qué hiciste y sucedió: https://github.com/mumuki/mumuki-platform/blob/master/CONTRIBUTING.md.

Pero si pensás que hay algún ejercicio que está mal o no te sale, entrá acá: https://www.facebook.com/groups/237784263357385/
