### ISSUE TITLE
Sometimes the user data is requested twice after joining to a course

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#862]
@fedescarpa please explain the issue here

**Comment by fedescarpa** [comment]
Cuando se une por primera vez a un curso usando el link de JOIN le pide sus datos (Nombre, Apellido y Mail). Si además no tiene nombre y apellido en su profile, se lo vuelve a preguntar... 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1039278/33331054-512f0c12-d43f-11e7-81d9-5d57a9e3cd21.gif)

**Comment by flbulgarelli** [comment]
Rising priority
