### ISSUE TITLE
ERD & Tables are not being properly displayed

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-laboratory#895]
After clicking the next button in an exercise view or clicking in the "status breadcrumb" to navigate to another exercise, erd, tables, browser and all other mumuki-styles components are not being displayed. If your reload the browser they appear.

<img width="1440" alt="screen shot 2018-01-16 at 16 01 32" src="https://user-images.githubusercontent.com/4105740/35006944-c3cec1be-fad6-11e7-80c2-41f9a8fbb089.png">

<img width="1440" alt="screen shot 2018-01-16 at 16 01 35" src="https://user-images.githubusercontent.com/4105740/35006943-c3ab8794-fad6-11e7-8301-f255bbd4cf35.png">

**Comment by fedescarpa** [comment]
I can't find the problem. I don't know why `mumuki.load` function of any mumuki styles component is not being called when user navigate the page.

Maybe it was an issue of turbolinks + styles. I Should check it

**Comment by fedescarpa** [comment]
Fixed in https://github.com/mumuki/mumuki-laboratory/commit/4d44a7bd75c883a0d797919e402b7ff65a7a8caa
