### ISSUE TITLE
Soporte para bloques

### ISSUE THREAD

**Issue by rodri042** [mumuki/mumuki-laboratory#898]
Estuve jugando con esto: https://www.youtube.com/watch?v=SRFRi7Cd9JQ

 Está todo medio cableado, pero lo que pensaba hacer era:
- Hacer una gema con `gs-element-blockly` de forma similar a lo que hicimos con gs-board
- Agregar un tipo más al enum de `editor` que sea `:custom`
- Los runners en la metadata pasarían a exponer un campo `custom_editor` que tiene `{ html: 'assets/gs-element-blockly.html', js: 'assets/gs-element-blockly.js', css: 'assets/gs-element-blockly.css' }` (por ejemplo)
- Este campo lo importan `mumukit_bridge` y `laboratory`
- Cuando el `editor` del `exercise` es `:custom` se importan los assets del `custom_editor` del runner y lo muestra
- Los `layouts` no se tocan, por lo que se podrían usar los mismos layouts con el nuevo editor

**Comment by flbulgarelli** [comment]
> * Hacer una gema con gs-element-blockly de forma similar a lo que hicimos con gs-board

:+1: 

> * Agregar un tipo más al enum de editor que sea :custom

:+1: 

> * Los runners en la metadata pasarían a exponer un campo custom_editor que tiene { html: 'assets/gs-element-blockly.html', js: 'assets/gs-element-blockly.js', css: 'assets/gs-element-blockly.css' } (por ejemplo)
Este campo lo importan mumukit_bridge y laboratory

:+1: 

> * Cuando el editor del exercise es :custom se importan los assets del custom_editor del runner y lo muestra

:+1: Pero cuidado, hay que tener en cuenta este issue https://github.com/mumuki/mumuki-laboratory/issues/884

> * Los layouts no se tocan, por lo que se podrían usar los mismos layouts con el nuevo editor

De acuerdo. De todas formas, me gustaría contar con un nuevo layout para primaria, independientemente de ésto.

**Comment by flbulgarelli** [comment]
Como dato extra, a tener en cuenta: como esbocé [acá](https://github.com/mumuki/mumuki-laboratory/pull/899#discussion_r162046320) me gustaría que también los runners pudieran exponer assets para renderizar un componente de submit personalizado. 

En el caso del soporte para bloques de gobstones-jr, ese componente debería: 

1. Permitir ejecutar el tablero en el cliente antes (o en paralelo) a validar el ejercicio contra el servidor, animando los resultados y pudiendo volver a ejecutarlo indefinidas veces.
2.  Ocupar menos lugar que el componente de envío actual, siendo un botón de _play_ superpuesto con el tablero como en [gobstones web](https://github.com/mumuki/mumuki-laboratory/pull/899#discussion_r162046320)

**Comment by flbulgarelli** [comment]
> Permitir ejecutar el tablero en el cliente antes (o en paralelo) a validar el ejercicio contra el servidor, animando los resultados y pudiendo volver a ejecutarlo indefinidas veces.

La ventaja de ejecutarlo en paralelo es que la respuesta al estudiante es mas veloz, no teniendo que esperar el viaje ida y vuelta al servidor para validar al ejercicio una vez terminada la ejecución del programa. 

La contra es que al estar cada ejecución asociada a una evaluación (lo cual creo que es deseable para mantener una interfaz gráfica simple), terminaría cargando al servidor más que ahora. Por el contrario, sólo enviar a validar al servidor soluciones que compilen (en el caso de bloques esto está garantizado, pero en gobstones común, no) y no produzcan boom es una gran optimización. 

Como punto intermedio, se podría enviar a validar sólo las soluciones que sean diferentes a la última enviada, para no reprocesar su evaluación. No iría por esta estrategia en primera instancia, y me gustaría que las otras dos opciones estén soportadas y parametrizadas de ser posible.

**Comment by flbulgarelli** [comment]
@rodri042 hay algo más que falte para poder cerrar este issue? Si no es el caso, continuemos la discusión sobre el botón de submit en un nuevo issue.

**Comment by rodri042** [comment]
No, cerralo nomás.

2018-01-18 19:39 GMT-03:00 Franco Leonardo Bulgarelli <
notifications@github.com>:
