### ISSUE TITLE
Rename custom-editor

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#901]
The selector `custom-editor` is used to render custom editors using JS - see https://github.com/mumuki/mumuki-laboratory/pull/899. 

I think it should be `mu-custom-editor` to avoid name clashes, and be a class, not an id. @fedescarpa what do you think?

**Comment by flbulgarelli** [comment]
Related to #898

**Comment by fedescarpa** [comment]
I think `mu-custom-editor` is better than 'custom-editor'

**Comment by flbulgarelli** [comment]
I don't find any references to `custom-editor` in the code. I only found this: 

https://github.com/mumuki/mumuki-laboratory/blob/3847a6d52e735efee549a450cf3e6316cc355d46/app/assets/stylesheets/application/modules/_kids.scss#L348

**Comment by flbulgarelli** [comment]
Also, I recently listed it here: https://github.com/mumuki/mumuki-laboratory#public-selectors

**Comment by flbulgarelli** [comment]
Closing
