### ISSUE TITLE
Links in flash notices look pretty bad

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mumuki-laboratory#904]
![image](https://user-images.githubusercontent.com/11720274/35281484-ca40be16-0031-11e8-9046-880260386ab2.png)

**Comment by flbulgarelli** [comment]
There are currently no links in flash notices. Closing

**Comment by julian-berbel** [comment]
![image](https://user-images.githubusercontent.com/11720274/35406887-e36e99f4-01e8-11e8-9c53-80d69c996233.png)
links in flash notices can't look bad if there are no links in flash notices.
