### ISSUE TITLE
Animations are always being reloaded

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#909]

**Comment by flbulgarelli** [comment]
Is this still happening? @julian-berbel @fedescarpa?

**Comment by julian-berbel** [comment]
error svgs are still always being reloaded. Yes.

**Comment by fedescarpa** [comment]
fixed in https://github.com/mumuki/mumuki-laboratory/commit/e54e6f37ca79cf643be15707bc2af84bcf291a56

**Comment by flbulgarelli** [comment]
Yes or no? I am confused...

**Comment by julian-berbel** [comment]
Never mind me. I thought you were asking if this had been solved as part of the turbolinks bug, which it hadn't. But it seems it was solved later and I didn't know about it.
