### ISSUE TITLE
Console not working in mobile browsers

### ISSUE THREAD

**Issue by Gustrucco** [mumuki/mumuki-laboratory#918]

**Comment by flbulgarelli** [comment]
Hi @Gustrucco, which device are you using?

**Comment by flbulgarelli** [comment]
It looks like it is happening in every device.

**Comment by flbulgarelli** [comment]
I tested it today and text is not inserted/rendered in the repl

**Comment by flbulgarelli** [comment]
Reopening. It now works _sometimes_, but not always.
