### ISSUE TITLE
Editor gutter is broken when gobstones assets are loaded

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#920]
It doesn't show up until you click the editor

**Comment by flbulgarelli** [comment]
![image](https://user-images.githubusercontent.com/677436/35685341-364b34a2-0748-11e8-91c2-69199d1cc961.png)

**Comment by flbulgarelli** [comment]
This happens even if the script is not actually loaded but just requested.

**Comment by luchotc** [comment]
Can't reproduce this bug in v 63.0.3239.132 of Chrome.
Probably related with turbolinks.
