### ISSUE TITLE
Error in web tools console

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-laboratory#926]
In Firefox this error is shown in the console:
`TypeError: 'closest' called on an object that does not implement interface Element.`

It is probably related to the addition of the webcomponents asset. One posible solution is to avoid using the entire webcomponents polyfill and use webcomponents-lite, which doesn't includes the polyfill for shadow DOM which apparently isn't required by Polymer as it has its own implementation of it.

**Comment by flbulgarelli** [comment]
@luchotc why was this closed? Did the issue just gone with the wind?

**Comment by luchotc** [comment]
Yes, that's exactly what happened!
