### ISSUE TITLE
Portugese translations

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-laboratory#940]
Missing translations:
Lesson -> lição
escreva en lugar de eu escrevi (en el placeholder)
En lugar de Eu continue -> continue (revisar esto en todos lados, no poner los pronombres en imperativo)
No se dice idioma, se dice linguagem.

**Comment by flbulgarelli** [comment]
Fixed long time ago in 4bf4535fac5fa3a4c9797351cbab823907ca2bbd
