### ISSUE TITLE
Allow custom editors to submit solutions programatically

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#943]
We need to generalize submission JS components so that they enable custom submit buttons provided by runners to submit code programatically. It should have a `Mumukit::Bridge`-like interface, but talk to the laboratory server instead of the runner. 

For example: 

```javascript
// the bridge should leverage the communication protocol. We should hide details about e.g.
// using ajax or websockets  
var bridge = new mumuki.bridge.Laboratory(exerciseId); 

// perhaps we could provide a synchronous interface, like now
bridge.runTests(content, function(response) {
  // response.status is passed/failed/errored/etc
 // response.testResults is an array of objects
 // response.responseType is structured/unstructured
 // response.feedback is an array of strings
 // response.expectationResults, is an array of object. Unlike the normal Mumukit::Bridge::Runner, those results should already be translated to human language. 
 // response.result
});
  
```

**Comment by fedescarpa** [comment]
In the response we need to add some I18n data (like the title: "All right", "Tu solución pasó todas las pruebas", "Sua solução passou todos os testes")

**Comment by flbulgarelli** [comment]
:up: Update as of comment https://github.com/mumuki/mumuki-laboratory/issues/944#issuecomment-367794656. The evaluation result in `Problem` should be like the following: 

```javascript
bridge.runTests(content, function(response) {
 // response.status is passed/failed/errored/etc
 // response.html
 // response.guide_finished_by_solution
 // response.class_for_progress_list_item
});  
```

**Comment by julian-berbel** [comment]
See 2a0d214c35b3501740ef75e7596ee5d71b30fb54.

Instead of passing the success callback function as a parameter, I opted for returning the AJAX promise to allow adding callbacks for different scenarios.

**Comment by rodri042** [comment]
@julian-berbel could you change `runTests` to accept a second parameter for the extra code?

Currently the extra code is XML so we need a way to send the compiled code to the runner. I think that calling `runTest` with a second parameter should override the extra code of the exercise.

**Comment by flbulgarelli** [comment]
Done in b5da9ecbeef540cbdce563ef67ece26fc2255535
