### ISSUE TITLE
Render test results on the client

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#944]
Currently, the test results are rendered in the server, as part of an html-ajax response. 

However, in order to support submission of content programatically, we should answer a JSON, and render it on the client using JS.  

Related to #943

**Comment by julian-berbel** [comment]
After discussing this we've decided to keep rendering the HTML on the server, but also make the response a JSON, where the rendered html would be one of its fields.

**Comment by julian-berbel** [comment]
Response JSON now includes:
* class_for_progress_list_item
* guide_finished_by_solution
* html
* status

Plus, on try exercises:
* query_result
* result
