### ISSUE TITLE
Recognize gobstones primitives in extra content

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-laboratory#960]
Add support for recognizing primitives in extra content, so that student can use them.

**Comment by rodri042** [comment]
Done!

**Comment by flbulgarelli** [comment]
How does this work now?

**Comment by rodri042** [comment]
Now the extra code is XML so the runner's `editor.js` has to compile it, and it'll need to send the compiled extra code to the bridge interface (that's a pending issue: https://github.com/mumuki/mumuki-laboratory/issues/943#issuecomment-374101204).

But, having the compiled code directly on the `extra` field would be much more transparent in my opinion, so it needs some discussing.
