### ISSUE TITLE
Translation missing "ES" expectations

### ISSUE THREAD

**Issue by argdaniellarrea** [mumuki/mumuki-laboratory#962]
Everything else related seems to be working fine, inside the Functional Programming guide, at Guards and Patterns exercises, is it showing the error when showing the expectations texts.

This is happening on other guides to.

Just in case, the specs where the bug is happening:
 Win 10 English version with ES input, 
and Chrome on both modes (normal and incognito).

Img attached for more details:
![chrome_2018-03-20_11-37-07](https://user-images.githubusercontent.com/4080574/37662353-a8c518ec-2c35-11e8-812f-7dee1f3e0766.png)

**Comment by flbulgarelli** [comment]
Fixes in https://github.com/mumuki/mumuki-laboratory/issues/966
