### ISSUE TITLE
Pagina inexistente java

### ISSUE THREAD

**Issue by MatiasPardo** [mumuki/mumuki-laboratory#968]
Hola buenas, 
Trate de ingresar a la pagina de mumuki para hacer las lecciones pero me encontre con que el link no existe. 

Saludos,
Matias Pardo
Viernes noche.

**Comment by flbulgarelli** [comment]
Por favor consultá directamente con tu docente. Aquí solo se atacan cuestiones del desarrollo de la plataforma en sí.
