### ISSUE TITLE
Missing reset exercise button

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-laboratory#975]
Otherwise we can't get default code any more

**Comment by luchotc** [comment]
We should discuse the layout for this issue and #974 

With the compass rose added, the current layout is this:

![layout](https://user-images.githubusercontent.com/11860076/38505931-d312b2d0-3bee-11e8-92b1-3ce8fb6ede1b.png)

Don't pay attention to the scrollbars, they are thicker in my layout for some reason.

Where should we put the reset button to get default content back, and what icon should we use?

**Comment by flbulgarelli** [comment]
> Where should we put the reset button to get default content back,

What about between the trash and the play button? 

> and what icon should we use?


We should use https://fontawesome.com/v4.7.0/icon/undo/
