### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by JulianHauret** [mumuki/mumuki-laboratory#981]
Buenas tardes/noches/dias. cuando intento entrar en mumuki me larga error 500 y yo no se como solucionarlo intente de todo pero no me deja si ustedes me pudieran ayudar se los agradeceria

**Comment by flbulgarelli** [comment]
¿Cómo fue que obtuviste ese error? ¿Podés contarnos cómo reproducirlo?

**Comment by flbulgarelli** [comment]
Cerrando. Reabrir cuando haya más feedback.
