### ISSUE TITLE
Choice exercises are not working

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mumuki-laboratory#995]
The commit at fault is 132e6adb2b85ec81c86f343b543cda3e9e6f9d30. (Sorry, it was my bad.)

As part of implementing the submission logic with the js bridge, I made it so the solution would be taken from the codemirror editors in the page, which I didn't realise at the time excluded single and multiple choice exercises.

I tried changing it so it would instead make the solution everything in the form:
```
var content = {};
$('.new_solution').serializeArray().forEach(function(it) {
   content[it.name] = it.value;
});

return content;
```

While this did fix choice exercises, it also broke editor exercises because the value for the codemirror editor is calculated, and it doesn't change together with the written text.

I'll keep trying to find a solution that works for both types of exercises for now.

Then again, a possible solution could also be just reverting the aforementioned commit and leaving bridge to be used by custom editors.

**Comment by julian-berbel** [comment]
ok, so a possible solution to that unsync between the editor content and value could using editor.save() which seems to update the textarea's value, so it would be the previous code, plus prepending:
```
mumuki.page.editors.each(function (_, editor) {
  editor.save();
});
```
This seems like a bad solution though. Thoughts, @flbulgarelli?

**Comment by flbulgarelli** [comment]
> This seems like a bad solution though. Thoughts, @flbulgarelli?
Bad? Why? I actually like it.

**Comment by flbulgarelli** [comment]
Actually I didn't notice that we were reading from codemirror directly when I merge it, but I think that IS a bad idea to couple to the editor.

**Comment by flbulgarelli** [comment]
I think that in version `~> 4.x` of labo the JS was actually reading from the textarea, and that choices are writing to it, too.
